In [3]:
# 1. 字符串里的 +， *

pre = "py"

pre + "thon"  #'python'

pre * 3  # pypypy

# 2. list 中的 +， *

a = [1, 2, 3]

a + a  # [1, 2, 3, 1, 2, 3]
a * 3  # [1, 2, 3, 1, 2, 3, 1, 2, 3]

# 3. len(), append(), extend(),insert(i,x), remove(x) list.pop(i)
# list.clear(), index(x), count(x), sort(), reverse(), copy() = a[:]
#

# 4. range() 等差函数
# range(stop) -> range object
# range(start, stop[, step]) -> range object

range(0, 10, 3)  # 0,3,6,9

# 5. enumerate()

[[i, j] for i, j in enumerate(range(3))]  # [[0, 0], [1, 1], [2, 2]]

# 6. break 循环终止  continue: 结束本次循环，开始下一次

# 7. pass:

# def f(arg): pass    # a function that does nothing (yet)
# class C: pass       # a class with no methods (yet)

# 8. 匿名函数 lambda

f = lambda a, b: a + b

f(2, 3)  # 5

# 9. zip
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]

list(zip(*matrix))  # [(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

[[i, j] for i, j in zip(a, b)]  # [[1, 5], [2, 6], [3, 7], [4, 8]]

# 10.  元组 （）， 集合 set(),
a0 = ('abracadabra')  # 'abracadabra'
a = set('abracadabra')  # {'a', 'b', 'c', 'd', 'r'}

# 11. 字典

tel = {'jack': 4098, 'sape': 4139}

tel.keys()  # dict_keys(['jack', 'sape'])

list(tel.keys())  # ['jack', 'sape']

tel.values()  # dict_values([4098, 4139])

'guido' in tel  # False

'guido' not in tel  # True

d = dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

d  # {'sape': 4139, 'guido': 4127, 'jack': 4098}

{x: x**2 for x in (2, 4, 6)}  # {2: 4, 4: 16, 6: 36}

# d.items()   enumerate() , zip(), reversed(),倒位 ；
# 使用 sorted() 函数，它不改动原序列，而是生成一个新的已排序的序列:

knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.items():
    print(k, v)

# in， not in
# is, not is
# and or not B

# 12. dir()

import numpy as np
dir(np)

# 13. 也可以用 ‘**’ 标志将这个字典以关键字参数的方式传入 函数

# 14. 通过 self 参数的方法属性，方法可以调用其它的方法:


class Bag:
    def __init__(self):
        self.data = []

    def add(self, x):
        self.data.append(x)

    def addtwice(self, x):
        self.add(x)
        self.add(x)
        
        
# 15. 名称重整是有助于子类重写方法，而不会打破组内的方法调用。例如:



[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [36]:
class Mapping:
    def __init__(self, iterable):
        self.items_list = []
        self.__update(iterable)

    def update(self, iterable):
        for item in iterable:
            self.items_list.append(item)

    __update = update  # private copy of original update() method


class MappingSubclass(Mapping):
    def update(self, keys, values):
        # provides new signature for update()
        # but does not break __init__()
        for item in zip(keys, values):
            self.items_list.append(item)
        

C = MappingSubclass([1,2])
C.update([1,2], ['ss','rr'])



In [38]:
import os

os.getcwd(
)  # 返回当前的路径 '/Users/snszz/Desktop/hybrid subspace learning/hybrid_sl_code_python/hybrid_pacakage/practice'

os.system('mkdir today')

dir(os)

help(os)

import pandas as pd

dir(pd)

dir(list)  # 返回方法（函数）名称



0

In [81]:
# numpy 学习
"""
1. numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

object	数组或嵌套的数列
dtype	数组元素的数据类型，可选
copy	对象是否需要复制，可选
order	创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）
subok	默认返回一个与基类类型一致的数组
ndmin	指定生成数组的最小维度

"""

#1.1  dtype 参数
import numpy as np
a = np.array([1, 2, 3], dtype=complex)
print(a)  #[ 1.+0.j,  2.+0.j,  3.+0.j]
"""


# 2. numpy.asarray(a, dtype = None, order = None)
# numpy.asarray 类似 numpy.array，但 numpy.asarray 参数只有三个，比 numpy.array 少两个。
"""

a = np.asarray([1, 2, 3])  # array([1, 2, 3])
"""
3. numpy.arange(start, stop, step, dtype)

start	起始值，默认为0
stop	终止值（不包含）
step	步长，默认为1
dtype	返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。

"""
x = np.arange(10, 20, 2)  # [10  12  14  16  18]
"""
4. 数列 
4.1 np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

start	序列的起始值
stop	序列的终止值，如果endpoint为true，该值包含于数列中
num	要生成的等步长的样本数量，默认为50
endpoint	该值为 true 时，数列中包含stop值，反之不包含，默认是True。
retstep	如果为 True 时，生成的数组中会显示间距，反之不显示。
dtype	ndarray 的数据类型


4.2 np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)

start	序列的起始值为：base ** start
stop	序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中
num	要生成的等步长的样本数量，默认为50
endpoint	该值为 true 时，数列中中包含stop值，反之不包含，默认是True。
base	对数 log 的底数。
dtype	ndarray 的数据类型
"""
np.linspace(1, 10, 10)  # [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

np.linspace(-10, 0, 5, endpoint = False)  # [-10.,  -8.,  -6.,  -4.,  -2.]

a =np.linspace(1,10,10,retstep= True) # (array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)
# 扩展
b =np.linspace(1,10,10).reshape([10,1])

#等比
a = np.logspace(1.0,  2.0, num =  10) 

a = np.logspace(0,9,10,base=2)  # [  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]

"""
5. 切片

5.1 start:stop:step 设置起始，终止和步长的参数为 2，7 和 2

5.2 a[i:]

5.3 布尔索引  x[x >  5]

5.4  ~（取补运算符）来过滤 NaN

a = np.array([np.nan,  1,2,np.nan,3,4,5])  
print (a[~np.isnan(a)])

5.5 x=np.arange(32).reshape((8,4))

5.6、传入多个索引数组（要使用np.ix_）

x=np.arange(32).reshape((8,4))
print (x[np.ix_([1,5,7,2],[0,3,1,2])])

x[1,0] x[1,3] x[1,1] x[1,2]
x[5,0] x[5,3] x[5,1] x[5,2]
x[7,0] x[7,3] x[7,1] x[7,2]
x[2,0] x[2,3] x[2,1] x[2,2]


"""

"""
6. NumPy 广播(Broadcast)

广播(Broadcast)是 numpy 对不同形状(shape)的数组进行数值计算的方式，
对数组的算术运算通常在相应的元素上进行。

6.1 如果两个数组 a 和 b 形状相同，即满足 a.shape == b.shape，
那么 a*b 的结果就是 a 与 b 数组对应位相乘。这要求维数相同，
且各维度的长度相同。

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40])  

c = a * b  # [ 10  40  90 160]


6.2 当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制。如：

import numpy as np 
 
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
 
 
 import numpy as np 
 
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
bb = np.tile(b, (4, 1))  # 重复 b 的各个维度
print(a + bb)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
 
b = np.array([1,2,3])
bb = np.tile(b, (4, 1))  # 重复 b 的各个维度

[[1, 2, 3],
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]]

"""

"""
7. Numpy 数组操作

7.1修改数组形状

7.1.1 reshape	不改变数据的条件下修改形状
7.1.2 flat	数组元素迭代器

a  = np.arange(8).reshape(4,2)

[i for i in a.flat]  # [0, 1, 2, 3, 4, 5, 6, 7]

7.1.3 flatten	返回一份数组拷贝，对拷贝所做的修改不会影响原始数组

# ndarray.flatten(order='C')

order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。

print (a.flatten())   # [0, 1, 2, 3, 4, 5, 6, 7]

7.1.4ravel	返回展开数组, ，修改会影响原始数组。

numpy.ravel(a, order='C')

order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。

a.ravel()  # [0, 1, 2, 3, 4, 5, 6, 7]


7.2 翻转数组

7.2.1 transpose	对换数组的维度

numpy.transpose(arr, axes)


7.2.2 ndarray.T	和 self.transpose() 相同

7.2.3 rollaxis	向后滚动指定的轴

7.2.4 swapaxes	对换数组的两个轴

numpy.swapaxes(arr, axis1, axis2)

arr：输入的数组
axis1：对应第一个轴的整数
axis2：对应第二个轴的整数

7.3 连接数组
7.3.1 concatenate	连接沿现有轴的数组序列

numpy.concatenate((a1, a2, ...), axis)
a1, a2, ...：相同类型的数组
axis：沿着它连接数组的轴，默认为 0

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.concatenate((a,b))

沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
 
np.concatenate((a,b),axis = 1)
沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]

7.3.3 stack	沿着新的轴加入一系列数组。

numpy.stack(arrays, axis)


arrays相同形状的数组序列
axis：返回数组中的轴，输入数组沿着它来堆叠

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.stack((a,b),0)

沿轴 0 堆叠两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

np.stack((a,b),1)

沿轴 1 堆叠两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]

7.3.3 hstack	水平堆叠序列中的数组（列方向）

np.hstack((a,b))

水平堆叠：
[[1 2 5 6]
 [3 4 7 8]]
 
7.3.4 vstack	竖直堆叠序列中的数组（行方向）

np.vstack(a, b)

竖直堆叠：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

7.4 分割数组

7.4.1 split	将一个数组分割为多个子数组

numpy.split(ary, indices_or_sections, axis)
ary：被分割的数组
indices_or_sections：果是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭）
axis：沿着哪个维度进行切向，默认为0，横向切分。为1时，纵向切分

a = np.arange(9)
np.split(a,3)

将数组在一维数组中表明的位置分割：
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

np.split(a,[4,7])

将数组分为三个大小相等的子数组：
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


7.4.2 hsplit	将一个数组水平分割为多个子数组（按列）

7.4.3 vsplit	将一个数组垂直分割为多个子数组（按行）


7.5 数组元素的添加与删除

7.5.1 resize	返回指定形状的新数组

numpy.resize(arr, shape)
arr：要修改大小的数组
shape：返回数组的新形状

ex. 
a = np.array([[1,2,3],[4,5,6]])
np.resize(a, (3,2))

7.5.2 append	将值添加到数组末尾

numpy.append(arr, values, axis=None)

arr：输入数组
values：要向arr添加的值，需要和arr形状相同（除了要添加的轴）
axis：默认为 None。当axis无定义时，是横向加成，返回总是为一维数组！
当axis有定义的时候，分别为0和1的时候。当axis有定义的时候，
分别为0和1的时候（列数要相同）。当axis为1时，数组是加在右边（行数要相同）。

np.append(a, [[7,8,9]],axis = 0)

沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]
np.append(a, [[5,5,5],[7,8,9]],axis = 1)

沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]

7.5.3 insert	沿指定轴将值插入到指定下标之前

numpy.insert(arr, obj, values, axis)
arr：输入数组
obj：在其之前插入值的索引
values：要插入的值
axis：沿着它插入的轴，如果未提供，则输入数组会被展开

ex. 
a = np.array([[1,2],[3,4],[5,6]])

np.insert(a,3,[11,12])

未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]

np.insert(a,1,[11],axis = 0)

传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴 0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]

np.insert(a,1,11,axis = 1)

沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]

7.5.4 delete	删掉某个轴的子数组，并返回删除后的新数组

Numpy.delete(arr, obj, axis)
参数说明：

arr：输入数组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组
axis：沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开

a = np.arange(12).reshape(3,4)

np.delete(a,5)

未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]

np.delete(a,1,axis = 1)

删除第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


np.delete(a, np.s_[::2])

包含从数组中删除的替代值的切片：
[ 2  4  6  8 10]

7.5.5 unique	查找数组内的唯一元素  (用于去除数组中的重复元素。)

numpy.unique(arr, return_index, return_inverse, return_counts)

arr：输入数组，如果不是一维数组则会展开
return_index：如果为true，返回新列表元素在旧列表中的位置（下标），并以列表形式储
return_inverse：如果为true，返回旧列表元素在新列表中的位置（下标），并以列表形式储
return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数

ex. 
a = np.array([5,2,6,2,7,5,6,8,2,9])
np.unique(a)

第一个数组的去重值：
[2 5 6 7 8 9]

u,indices = np.unique(a, return_index = True)
u 
去重数组的索引数组：
[1 0 2 4 7 9]


u,indices = np.unique(a,return_inverse = True)
u 
去重数组的下标：
[2 5 6 7 8 9]

indices 
下标为：
[1 0 2 0 3 1 2 4 0 5]

u[indices]
使用下标重构原数组：
[5 2 6 2 7 5 6 8 2 9]

u,indices = np.unique(a,return_counts = True)

返回去重元素的重复数量：
u 
[2 5 6 7 8 9]

indices
[3 2 2 1 1 1] 

"""


"""


8.  NumPy 位运算

bitwise_and	对数组元素执行位与操作
bitwise_or	对数组元素执行位或操作
invert	按位取反
left_shift	向左移动二进制表示的位
right_shift	向右移动二进制表示的位

a,b = 13,17
bin(a), bin(b)
np.bitwise_and(13, 17)

np.bitwise_and(13, 17)

np.invert(np.array([13], dtype = np.uint8))  # 反
 # 242
    
np.binary_repr(13, width = 8)
# 00001101
13 的二进制表示：
00001101

"""
"""


9 . NumPy 字符串函数

https://www.runoob.com/numpy/numpy-string-functions.html


9.1 add()	对两个数组的逐个字符串元素进行连接

np.char.add(['hello', 'hi'],[' abc', ' xyz'])


9.2 multiply()	返回按元素多重连接后的字符串

np.char.multiply('Runoob ',3)

9.3 center()	居中字符串

np.char.center('Runoob', 20,fillchar = '*')

# *******Runoob*******

9.4 capitalize()	将字符串第一个字母转换为大写
 
 np.char.capitalize('runoob')
 
9.5 title()	将字符串的每个单词的第一个字母转换为大写
 
 np.char.title('i like runoob')
 
 # I Like Runoob
 
9.6 lower()	数组元素转换为小写

 np.char.lower(['RUNOOB','GOOGLE']
 
 # ['runoob' 'google']
 
9.7 upper()	数组元素转换为大写
 
 np.char.upper(['runoob','google'])
 
9.8 split()	指定分隔符对字符串进行分割，并返回数组列表
 
 np.char.split ('www.runoob.com', sep = '.')
 # ['www', 'runoob', 'com']
 
9.9 splitlines()	返回元素中的行列表，以换行符分割  \n，\r，\r\n 都可用作换行符。
 
 np.char.splitlines('i\nlike runoob?')
  # ['i', 'like runoob?']
  
 
9.10 strip()	移除元素开头或者结尾处的特定字符
 
 np.char.strip(['arunooba','admin','java'],'a')
 #  ['runoob' 'dmin' 'jav']
 
9.11 join()	通过指定分隔符来连接数组中的元素
 
 
 # 操作字符串
print (np.char.join(':','runoob'))  #r:u:n:o:o:b
 
# 指定多个分隔符操作数组元素
print (np.char.join([':','-'],['runoob','google']))

# ['r:u:n:o:o:b' 'g-o-o-g-l-e']

9.12 replace()	使用新字符串替换字符串中的所有子字符串
 
 np.char.replace ('i like runoob', 'oo', 'cc')
 
 # i like runccb
 
9.13 decode()	数组元素依次调用str.decode
 
 a = np.char.encode('runoob', 'cp500') 
print (a)
print (np.char.decode(a,'cp500'))
 
#  b'\x99\xa4\x95\x96\x96\x82'
# runoob
 
9.14 encode()	数组元素依次调用str.encode

np.char.encode('runoob', 'cp500') 
 
 # b'\x99\xa4\x95\x96\x96\x82'
 
"""


"""

10. NumPy 数学函数

1.0.1 np.sin() , np.cos(), np.tan()

10.2 舍入函数
numpy.around() 函数返回指定数字的四舍五入值。

numpy.around(a,decimals)
参数说明：

a: 数组
decimals: 舍入的小数位数。 默认值为0。 如果为负，整数将四舍五入到小数点左侧的位置

a = np.array([1.0,5.55,  123,  0.567,  25.532])  

np.around(a)  # 舍入后：[  1.   6. 123.   1.  26.]



np.around(a, decimals =  1)  # [  1.    5.6 123.    0.6  25.5]

np.around(a, decimals =  -1)  # [  0.  10. 120.   0.  30.]

10.2.2
numpy.floor() 返回小于或者等于指定表达式的最大整数，即向下取整。

a = np.array([-1.7,  1.5,  -0.2,  0.6,  10])

np.floor(a)  # [-2.  1. -1.  0. 10.]

10.2.3
numpy.ceil() 返回大于或者等于指定表达式的最小整数，即向上取整。

a = np.array([-1.7,  1.5,  -0.2,  0.6,  10]) 

np.ceil(a) # [-1.  2. -0.  1. 10.]

"""


"""
11. NumPy 算术函数

NumPy 算术函数包含简单的加减乘除: add()，subtract()，multiply() 和 divide()。

需要注意的是数组必须具有相同的形状或符合数组广播规则。

np.add(a,b) 

np.subtract(a,b)

np.multiply(a,b)

np.divide(a,b) 

numpy.reciprocal(a)   # 函数返回参数逐元素的倒数。如 1/4 倒数为 4/1。

numpy.power(底数， 幂)  #函数将第一个输入数组中的元素作为底数，计算它与第二个输入数组中相应元素的幂。

a = np.array([10,100,1000]) 

np.power(a,2)

b = np.array([1,2,3])  
np.power(a,b）         # [        10      10000 1000000000]

numpy.mod()            # 计算输入数组中相应元素的相除后的余数。 函数 numpy.remainder() 也产生相同的结果。
numpy.remainder()     # 计算输入数组中相应元素的相除后的余数


numpy.ptp()函数计算数组中元素最大值与最小值的差（最大值 - 最小值）。

a = np.array([[3,7,5],[8,4,3],[2,4,9]])

np.ptp(a)  # 总

np.ptp(a, axis =  0) #行 

np.ptp(a, axis =  1) #列 


numpy.median() 函数用于计算数组 a 中元素的中位数（中值）

numpy.mean() 函数返回数组中元素的算术平均值。 如果提供了轴，则沿其计算。

numpy.average() 函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值。

np.std()
np.var()


"""


"""

12. NumPy 排序、条件刷选函数

numpy.sort() 函数返回输入数组的排序副本。函数格式如下：

a: 要排序的数组
axis: 沿着它排序数组的轴，如果没有数组会被展开，沿着最后的轴排序， axis=0 按列排序，axis=1 按行排序
kind: 默认为'quicksort'（快速排序）
order: 如果数组包含字段，则是要排序的字段

numpy.argsort() 函数返回的是数组值从小到大的索引值。


numpy.argmax() 
numpy.argmin()函数分别沿给定轴返回最大和最小元素的索引。


numpy.nonzero() 函数返回输入数组中非零元素的索引。

numpy.where() 函数返回输入数组中满足给定条件的元素的索引。

a = np.arange(10)

np.where(a < 5, a, 10*a)

# array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

ex. 

a = np.array([[0, 1, 2], [0, 2, 4], [0, 3, 6]])
np.where(a < 4, a, -1)  # -1 is broadcast


# array([[0, 1, 2], [0, 2, -1], [0, 3, -1]])
# 满足条件就返回a中对应的值，不满足条件就返回定义的广播值

numpy.extract() 函数根据某个条件从数组中抽取元素，返回满条件的元素。


x = np.arange(9.).reshape(3,  3)  

condition = np.mod(x,2)  ==  0  

np.extract(condition, x)  # <=====> x[x % 2 == 0]  <=====> x[np.mod(x,2)  ==  0 ]

# [0., 2., 4., 6., 8.]
"""

"""

13. NumPy 矩阵库(Matrix)

NumPy 中包含了一个矩阵库 numpy.matlib，该模块中的函数返回的是一个矩阵，
1. 转置 np.transpose(); A.T

2. np.zeros(), np.ones(), np.eye()
"""

"""

14. NumPy 线性代数

NumPy 提供了线性代数函数库 linalg，该库包含了线性代数所需的所有功能，可以看看下面的说明：

1. dot	两个数组的点积，即元素对应相乘。

a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(np.dot(a,b))  # [[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]


2. vdot	两个向量的点积

a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
 
# vdot 将数组展开计算内积  1*11 + 2*12 + 3*13 + 4*14 = 130
print (np.vdot(a,b))


3. inner	两个数组的内积
numpy.inner() 函数返回一维数组的向量内积。对于更高的维度，它返回最后一个轴上的和的乘积。



4. matmul	两个数组的矩阵积


5. determinant	数组的行列式

numpy.linalg.det() 函数计算输入矩阵的行列式。


6. solve	求解线性矩阵方程

numpy.linalg.solve() 函数给出了矩阵形式的线性方程的解。

7. inv	计算矩阵的乘法逆矩阵


import numpy as np 
 
a = np.array([[1,1,1],[0,2,5],[2,5,-1]]) 
 
print ('数组 a：')
print (a)
ainv = np.linalg.inv(a) 
 
print ('a 的逆：')
print (ainv)
 
print ('矩阵 b：')
b = np.array([[6],[-4],[27]]) 
print (b)
 
print ('计算：A^(-1)B：')
x = np.linalg.solve(a,b) 
print (x)
# 这就是线性方向 x = 5, y = 3, z = -2 的解

"""
"""

15. NumPy IO
Numpy 可以读写磁盘上的文本数据或二进制数据。

NumPy 为 ndarray 对象引入了一个简单的文件格式：npy。

npy 文件用于存储重建 ndarray 所需的数据、图形、dtype 和其他信息。

常用的 IO 函数有：

load() 和 save() 函数是读写文件数组数据的两个主要函数，默认情况下，数组是以未压缩的原始二进制格式保存在扩展名为 .npy 的文件中。
savez() 函数用于将多个数组写入文件，默认情况下，数组是以未压缩的原始二进制格式保存在扩展名为 .npz 的文件中。
loadtxt() 和 savetxt() 函数处理正常的文本文件(.txt 等)


1. numpy.save()
numpy.save() 函数将数组保存到以 .npy 为扩展名的文件中。
参数说明：

file：要保存的文件，扩展名为 .npy，如果文件路径末尾没有扩展名 .npy，该扩展名会被自动加上。
arr: 要保存的数组
allow_pickle: 可选，布尔值，允许使用 Python pickles 保存对象数组，Python 中的 pickle 用于在保存到磁盘文件或从磁盘文件读取之前，对对象进行序列化和反序列化。
fix_imports: 可选，为了方便 Pyhton2 中读取 Python3 保存的数据。


ex. 
import numpy as np 
 
a = np.array([1,2,3,4,5]) 
 
# 保存到 outfile.npy 文件上
np.save('outfile.npy',a) 
 
# 保存到 outfile2.npy 文件上，如果文件路径末尾没有扩展名 .npy，该扩展名会被自动加上
np.save('outfile2',a)


2. 可以看出文件是乱码的，因为它们是 Numpy 专用的二进制格式后的数据。

我们可以使用 load() 函数来读取数据就可以正常显示了：

import numpy as np 
 
b = np.load('outfile.npy')  
print (b)

3.  np.savez
numpy.savez() 函数将多个数组保存到以 npz 为扩展名的文件中。

numpy.savez(file, *args, **kwds)
参数说明：

file：要保存的文件，扩展名为 .npz，如果文件路径末尾没有扩展名 .npz，该扩展名会被自动加上。
args: 要保存的数组，可以使用关键字参数为数组起一个名字，非关键字参数传递的数组会自动起名为 arr_0, arr_1, …　。
kwds: 要保存的数组使用关键字名称。
实例
import numpy as np 
 
a = np.array([[1,2,3],[4,5,6]])
b = np.arange(0, 1.0, 0.1)
c = np.sin(b)
# c 使用了关键字参数 sin_array
np.savez("runoob.npz", a, b, sin_array = c)
r = np.load("runoob.npz")  
print(r.files) # 查看各个数组名称
print(r["arr_0"]) # 数组 a
print(r["arr_1"]) # 数组 b
print(r["sin_array"]) # 数组 c


4. savetxt()
savetxt() 函数是以简单的文本文件格式存储数据，对应的使用 loadtxt() 函数来获取数据。

np.loadtxt(FILENAME, dtype=int, delimiter=' ')
np.savetxt(FILENAME, a, fmt="%d", delimiter=",")
参数 delimiter 可以指定各种分隔符、针对特定列的转换器函数、需要跳过的行数等。

实例
import numpy as np 
 
a = np.array([1,2,3,4,5]) 
np.savetxt('out.txt',a) 
b = np.loadtxt('out.txt')  
 
print(b)

"""


"""
16. 作图
'-'	实线样式
'--'	短横线样式
'-.'	点划线样式
':'	虚线样式
'.'	点标记
','	像素标记
'o'	圆标记
'v'	倒三角标记
'^'	正三角标记
'&lt;'	左三角标记
'&gt;'	右三角标记
'1'	下箭头标记
'2'	上箭头标记
'3'	左箭头标记
'4'	右箭头标记
's'	正方形标记
'p'	五边形标记
'*'	星形标记
'h'	六边形标记 1
'H'	六边形标记 2
'+'	加号标记
'x'	X 标记
'D'	菱形标记
'd'	窄菱形标记
'&#124;'	竖直线标记
'_'	水平线标记


’b'	蓝色
'g'	绿色
'r'	红色
'c'	青色
'm'	品红色
'y'	黄色
'k'	黑色
'w'	白色
"""


[1.+0.j 2.+0.j 3.+0.j]


''

In [96]:
import pandas as pd
1. 
pd.Series(
    data=None,
    index=None,
    dtype=None,
    name=None,
    copy=False,
    fastpath=False,
)

a = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
a

2. 
pd.DataFrame(
    data=None,
    index=None,
    columns=None,
    dtype=None,
    copy=False,
)

# 列添加
data = pd.DataFrame() 
data['one'] = [1,2,3]

# 列删除
del data['one']

# 行选择，添加和删除
data.loc[]  # 索引
data.iloc[] # 整数位置传递
data

# 添加行append
import pandas as pd

df = pd.DataFrame([[1, 2], [3, 4]], columns = ['a','b'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns = ['a','b'])

df = df.append(df2)


# 删除行

df = df.drop(0)



序列基本功能
S.No.	属性或方法	描述
1	axes	返回行轴标签的列表。
2	dtype	返回对象的dtype。
3	empty	如果series为空，则返回True。
4	ndim	根据定义1返回基础数据的维度数。
5	size	返回基础数据中元素的数量。
6	values	将该序列作为ndarray返回。
7	head()	返回前n行。
8	tail()	返回最后n行。

DataFrame基本功能
让我们现在了解DataFrame基本功能是什么。下表列出了DataFrame Basic功能中的重要属性或方法。

S.No.	属性或方法	描述
1	Ť	转置行和列。
2	axes	以行轴标签和列轴标签作为唯一成员返回列表。
3	dtypes	返回此对象中的dtypes。
4	empty	如果NDFrame完全为空[没有项目]，则为true; 如果任何轴的长度为0。
5	ndim	轴/阵列尺寸的数量。
6	shape	返回表示DataFrame维度的元组。
7	size	NDFrame中的元素数目。
8	values	NDFrame的Numpy表示。
9	head()	返回前n行。
10	tail()	返回最后n行。


S.No.	功能	描述
1	count()	非空观测值的数量
2	sum()	值的总和
3	mean()	价值的意义
4	median()	价值的中间值
5	mode()	价值观的模式
6	std()	价值观的标准差
7	min()	最小值
8	max()	最大值
9	abs()	绝对值
10	prod()	价值的产物
11	cumsum()	累计和
12	cumprod()	累积产品



[Int64Index([0, 1, 0, 1], dtype='int64'), Index(['a', 'b'], dtype='object')]