# numpy的相关知识

## np.array

In [1]:
# numpy 学习
"""
1. numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

object	数组或嵌套的数列
dtype	数组元素的数据类型，可选
copy	对象是否需要复制，可选
order	创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）
subok	默认返回一个与基类类型一致的数组
ndmin	指定生成数组的最小维度

"""

'\n1. numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)\n\nobject\t数组或嵌套的数列\ndtype\t数组元素的数据类型，可选\ncopy\t对象是否需要复制，可选\norder\t创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）\nsubok\t默认返回一个与基类类型一致的数组\nndmin\t指定生成数组的最小维度\n\n'

In [2]:
# 1.1  dtype 参数
import numpy as np
a =np.array([[1,2], [3,4]])

In [3]:
#1.1  dtype 参数
import numpy as np
a = np.array([1, 2, 3], dtype=complex)
print(a)  #[ 1.+0.j,  2.+0.j,  3.+0.j]

[1.+0.j 2.+0.j 3.+0.j]


###   np.array 转换为list

In [4]:
np.eye(2,2).tolist()

[[1.0, 0.0], [0.0, 1.0]]

##  numpy.asarray

numpy.asarray(a, dtype = None, order = None)

In [5]:
a = np.asarray([1, 2, 3])  # array([1, 2, 3])
a

array([1, 2, 3])

## numpy.arange

In [6]:
"""
3. numpy.arange(start, stop, step, dtype)

start	起始值，默认为0
stop	终止值（不包含）
step	步长，默认为1
dtype	返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。

"""

x = np.arange(10, 20, 2)  # [10  12  14  16  18]
x

array([10, 12, 14, 16, 18])

## 数列

###  np.linspace

在python库numpy 中提供了函数linspace和logspace函数用于生产等差数列和等比数列。

指定初始值、终止值、数量、是否包含终止值，默认为包含。

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [7]:
"""
start	序列的起始值
stop	序列的终止值，如果endpoint为true，该值包含于数列中
num	要生成的等步长的样本数量，默认为50
endpoint	该值为 true 时，数列中包含stop值，反之不包含，默认是True。
retstep	如果为 True 时，生成的数组中会显示间距，反之不显示。
dtype	ndarray 的数据类型

"""

np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### np.logspace

In [8]:
"""
4.2 np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)

start	序列的起始值为：base ** start
stop	序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中
num	要生成的等步长的样本数量，默认为50
endpoint	该值为 true 时，数列中中包含stop值，反之不包含，默认是True。
base	对数 log 的底数。
dtype	ndarray 的数据类型
"""

'\n4.2 np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)\n\nstart\t序列的起始值为：base ** start\nstop\t序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中\nnum\t要生成的等步长的样本数量，默认为50\nendpoint\t该值为 true 时，数列中中包含stop值，反之不包含，默认是True。\nbase\t对数 log 的底数。\ndtype\tndarray 的数据类型\n'

In [9]:
np.linspace(1, 10, 10)  # [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

np.linspace(-10, 0, 5, endpoint = False)  # [-10.,  -8.,  -6.,  -4.,  -2.]

a =np.linspace(1,10,10,retstep= True) # (array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)
# 扩展
b =np.linspace(1,10,10).reshape([10,1])

#等比
a = np.logspace(1.0,  2.0, num =  10) 

a = np.logspace(0,9,10,base=2)  # [  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]



## 切片

In [10]:
5. 切片

5.1 start:stop:step 设置起始，终止和步长的参数为 2，7 和 2

5.2 a[i:]

5.3 布尔索引  x[x >  5]

5.4  ~（取补运算符）来过滤 NaN

a = np.array([np.nan,  1,2,np.nan,3,4,5])  
print (a[~np.isnan(a)])

5.5 x=np.arange(32).reshape((8,4))

5.6、传入多个索引数组（要使用np.ix_）

x=np.arange(32).reshape((8,4))
print (x[np.ix_([1,5,7,2],[0,3,1,2])])

x[1,0] x[1,3] x[1,1] x[1,2]
x[5,0] x[5,3] x[5,1] x[5,2]
x[7,0] x[7,3] x[7,1] x[7,2]
x[2,0] x[2,3] x[2,1] x[2,2]



SyntaxError: invalid syntax (<ipython-input-10-be8352ab47e1>, line 1)

## NumPy 广播(Broadcast)

In [ ]:

6. 

广播(Broadcast)是 numpy 对不同形状(shape)的数组进行数值计算的方式，
对数组的算术运算通常在相应的元素上进行。

6.1 如果两个数组 a 和 b 形状相同，即满足 a.shape == b.shape，
那么 a*b 的结果就是 a 与 b 数组对应位相乘。这要求维数相同，
且各维度的长度相同。

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40])  

c = a * b  # [ 10  40  90 160]


6.2 当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制。如：

import numpy as np 
 
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a + b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
 
 
 import numpy as np 
 
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
bb = np.tile(b, (4, 1))  # 重复 b 的各个维度
print(a + bb)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
 
b = np.array([1,2,3])
bb = np.tile(b, (4, 1))  # 重复 b 的各个维度

[[1, 2, 3],
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]]

## Numpy 数组操作

### reshape,flat, flatatten, ravel

In [ ]:
7. Numpy 数组操作

7.1修改数组形状

7.1.1 reshape	不改变数据的条件下修改形状
7.1.2 flat	数组元素迭代器

a  = np.arange(8).reshape(4,2)

[i for i in a.flat]  # [0, 1, 2, 3, 4, 5, 6, 7]

7.1.3 flatten	返回一份数组拷贝，对拷贝所做的修改不会影响原始数组

# ndarray.flatten(order='C')

order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。

print (a.flatten())   # [0, 1, 2, 3, 4, 5, 6, 7]

7.1.4ravel	返回展开数组, ，修改会影响原始数组。

numpy.ravel(a, order='C')

order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。

a.ravel()  # [0, 1, 2, 3, 4, 5, 6, 7]


### 翻转数组  transpose, swapaxes


In [ ]:
7.2.1 transpose	对换数组的维度

numpy.transpose(arr, axes)


7.2.2 ndarray.T	和 self.transpose() 相同

7.2.3 rollaxis	向后滚动指定的轴

7.2.4 swapaxes	对换数组的两个轴

numpy.swapaxes(arr, axis1, axis2)

arr：输入的数组
axis1：对应第一个轴的整数
axis2：对应第二个轴的整数

### 连接数组concatenate, stack, hstack, vstack

In [ ]:

7.3.1 concatenate	连接沿现有轴的数组序列

numpy.concatenate((a1, a2, ...), axis)
a1, a2, ...：相同类型的数组
axis：沿着它连接数组的轴，默认为 0

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.concatenate((a,b))

沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
 
np.concatenate((a,b),axis = 1)
沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]

7.3.3 stack	沿着新的轴加入一系列数组。

numpy.stack(arrays, axis)


arrays相同形状的数组序列
axis：返回数组中的轴，输入数组沿着它来堆叠

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.stack((a,b),0)

沿轴 0 堆叠两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

np.stack((a,b),1)

沿轴 1 堆叠两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]

7.3.3 hstack	水平堆叠序列中的数组（列方向）

np.hstack((a,b))

水平堆叠：
[[1 2 5 6]
 [3 4 7 8]]
 
7.3.4 vstack	竖直堆叠序列中的数组（行方向）

np.vstack(a, b)

竖直堆叠：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

### 分割数组split， 

In [ ]:
7.4.1 split	将一个数组分割为多个子数组

numpy.split(ary, indices_or_sections, axis)
ary：被分割的数组
indices_or_sections：果是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭）
axis：沿着哪个维度进行切向，默认为0，横向切分。为1时，纵向切分

a = np.arange(9)
np.split(a,3)

将数组在一维数组中表明的位置分割：
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

np.split(a,[4,7])

将数组分为三个大小相等的子数组：
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


7.4.2 hsplit	将一个数组水平分割为多个子数组（按列）

7.4.3 vsplit	将一个数组垂直分割为多个子数组（按行）

### 数组元素的添加与删除resize, append, insert

In [ ]:
7.5.1 resize	返回指定形状的新数组

numpy.resize(arr, shape)
arr：要修改大小的数组
shape：返回数组的新形状

ex. 
a = np.array([[1,2,3],[4,5,6]])
np.resize(a, (3,2))

7.5.2 append	将值添加到数组末尾

numpy.append(arr, values, axis=None)

arr：输入数组
values：要向arr添加的值，需要和arr形状相同（除了要添加的轴）
axis：默认为 None。当axis无定义时，是横向加成，返回总是为一维数组！
当axis有定义的时候，分别为0和1的时候。当axis有定义的时候，
分别为0和1的时候（列数要相同）。当axis为1时，数组是加在右边（行数要相同）。

np.append(a, [[7,8,9]],axis = 0)

沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]
np.append(a, [[5,5,5],[7,8,9]],axis = 1)

沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]

7.5.3 insert	沿指定轴将值插入到指定下标之前

numpy.insert(arr, obj, values, axis)
arr：输入数组
obj：在其之前插入值的索引
values：要插入的值
axis：沿着它插入的轴，如果未提供，则输入数组会被展开

ex. 
a = np.array([[1,2],[3,4],[5,6]])

np.insert(a,3,[11,12])

未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]

np.insert(a,1,[11],axis = 0)

传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴 0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]

np.insert(a,1,11,axis = 1)

沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]

7.5.4 delete	删掉某个轴的子数组，并返回删除后的新数组

Numpy.delete(arr, obj, axis)
参数说明：

arr：输入数组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组
axis：沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开

a = np.arange(12).reshape(3,4)

np.delete(a,5)

未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]

np.delete(a,1,axis = 1)

删除第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


np.delete(a, np.s_[::2])

包含从数组中删除的替代值的切片：
[ 2  4  6  8 10]

### unique

In [ ]:
unique	查找数组内的唯一元素  (用于去除数组中的重复元素。)

numpy.unique(arr, return_index, return_inverse, return_counts)

arr：输入数组，如果不是一维数组则会展开
return_index：如果为true，返回新列表元素在旧列表中的位置（下标），并以列表形式储
return_inverse：如果为true，返回旧列表元素在新列表中的位置（下标），并以列表形式储
return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数

ex. 
a = np.array([5,2,6,2,7,5,6,8,2,9])
np.unique(a)

第一个数组的去重值：
[2 5 6 7 8 9]

u,indices = np.unique(a, return_index = True)
u 
去重数组的索引数组：
[1 0 2 4 7 9]


u,indices = np.unique(a,return_inverse = True)
u 
去重数组的下标：
[2 5 6 7 8 9]

indices 
下标为：
[1 0 2 0 3 1 2 4 0 5]

u[indices]
使用下标重构原数组：
[5 2 6 2 7 5 6 8 2 9]

u,indices = np.unique(a,return_counts = True)

返回去重元素的重复数量：
u 
[2 5 6 7 8 9]

indices
[3 2 2 1 1 1] 

## NumPy 位运算

In [ ]:
bitwise_and	对数组元素执行位与操作
bitwise_or	对数组元素执行位或操作
invert	按位取反
left_shift	向左移动二进制表示的位
right_shift	向右移动二进制表示的位

a,b = 13,17
bin(a), bin(b)
np.bitwise_and(13, 17)

np.bitwise_and(13, 17)

np.invert(np.array([13], dtype = np.uint8))  # 反
 # 242
    
np.binary_repr(13, width = 8)
# 00001101
13 的二进制表示：
00001101

## NumPy 字符串函数

In [ ]:
https://www.runoob.com/numpy/numpy-string-functions.html


9.1 add()	对两个数组的逐个字符串元素进行连接

np.char.add(['hello', 'hi'],[' abc', ' xyz'])


9.2 multiply()	返回按元素多重连接后的字符串

np.char.multiply('Runoob ',3)

9.3 center()	居中字符串

np.char.center('Runoob', 20,fillchar = '*')

# *******Runoob*******

9.4 capitalize()	将字符串第一个字母转换为大写
 
np.char.capitalize('runoob')
 
9.5 title()	将字符串的每个单词的第一个字母转换为大写
 
 np.char.title('i like runoob')
 
 # I Like Runoob
 
9.6 lower()	数组元素转换为小写

 np.char.lower(['RUNOOB','GOOGLE']
 
 # ['runoob' 'google']
 
9.7 upper()	数组元素转换为大写
 
 np.char.upper(['runoob','google'])
 
9.8 split()	指定分隔符对字符串进行分割，并返回数组列表
 
 np.char.split ('www.runoob.com', sep = '.')
 # ['www', 'runoob', 'com']
 
9.9 splitlines()	返回元素中的行列表，以换行符分割  \n，\r，\r\n 都可用作换行符。
 
 np.char.splitlines('i\nlike runoob?')
  # ['i', 'like runoob?']
  
 
9.10 strip()	移除元素开头或者结尾处的特定字符
 
 np.char.strip(['arunooba','admin','java'],'a')
 #  ['runoob' 'dmin' 'jav']
 
9.11 join()	通过指定分隔符来连接数组中的元素
 
 
 # 操作字符串
print (np.char.join(':','runoob'))  #r:u:n:o:o:b
 
# 指定多个分隔符操作数组元素
print (np.char.join([':','-'],['runoob','google']))

# ['r:u:n:o:o:b' 'g-o-o-g-l-e']

9.12 replace()	使用新字符串替换字符串中的所有子字符串
 
 np.char.replace ('i like runoob', 'oo', 'cc')
 
 # i like runccb
 
9.13 decode()	数组元素依次调用str.decode
 
 a = np.char.encode('runoob', 'cp500') 
print (a)
print (np.char.decode(a,'cp500'))
 
#  b'\x99\xa4\x95\x96\x96\x82'
# runoob
 
9.14 encode()	数组元素依次调用str.encode

np.char.encode('runoob', 'cp500') 
 
 # b'\x99\xa4\x95\x96\x96\x82'

## NumPy 数学函数

### np.sin() , np.cos(), np.tan()

### 舍入函数 numpy.around()

In [ ]:
numpy.around() 函数返回指定数字的四舍五入值。

numpy.around(a,decimals)
参数说明：

a: 数组
decimals: 舍入的小数位数。 默认值为0。 如果为负，整数将四舍五入到小数点左侧的位置

a = np.array([1.0,5.55,  123,  0.567,  25.532])  

np.around(a)  # 舍入后：[  1.   6. 123.   1.  26.]



np.around(a, decimals =  1)  # [  1.    5.6 123.    0.6  25.5]

np.around(a, decimals =  -1)  # [  0.  10. 120.   0.  30.]

### numpy.floor()

In [ ]:
umpy.floor() 返回小于或者等于指定表达式的最大整数，即向下取整。

a = np.array([-1.7,  1.5,  -0.2,  0.6,  10])

np.floor(a)  # [-2.  1. -1.  0. 10.]

### numpy.ceil()

In [ ]:
numpy.ceil() 返回大于或者等于指定表达式的最小整数，即向上取整。

a = np.array([-1.7,  1.5,  -0.2,  0.6,  10]) 

np.ceil(a) # [-1.  2. -0.  1. 10.]

## NumPy 算术函数

NumPy 算术函数包含简单的加减乘除: add()，subtract()，multiply() 和 divide()。

需要注意的是数组必须具有相同的形状或符合数组广播规则。

In [ ]:
np.add(a,b) 

np.subtract(a,b)

np.multiply(a,b)

np.divide(a,b) 

numpy.reciprocal(a)   # 函数返回参数逐元素的倒数。如 1/4 倒数为 4/1。

numpy.power(底数， 幂)  #函数将第一个输入数组中的元素作为底数，计算它与第二个输入数组中相应元素的幂。

a = np.array([10,100,1000]) 

np.power(a,2)

b = np.array([1,2,3])  
np.power(a,b）         # [        10      10000 1000000000]

numpy.mod()            # 计算输入数组中相应元素的相除后的余数。 函数 numpy.remainder() 也产生相同的结果。
numpy.remainder()     # 计算输入数组中相应元素的相除后的余数


numpy.ptp()函数计算数组中元素最大值与最小值的差（最大值 - 最小值）。

a = np.array([[3,7,5],[8,4,3],[2,4,9]])

np.ptp(a)  # 总

np.ptp(a, axis =  0) #行 

np.ptp(a, axis =  1) #列 


numpy.median() 函数用于计算数组 a 中元素的中位数（中值）

numpy.mean() 函数返回数组中元素的算术平均值。 如果提供了轴，则沿其计算。

numpy.average() 函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值。

np.std()
np.var()


## NumPy 排序、条件刷选函数

### numpy.sort()

### numpy.argsort()

### numpy.argmax()

### numpy.where()

In [ ]:
numpy.sort() 函数返回输入数组的排序副本。函数格式如下：

a: 要排序的数组
axis: 沿着它排序数组的轴，如果没有数组会被展开，沿着最后的轴排序， axis=0 按列排序，axis=1 按行排序
kind: 默认为'quicksort'（快速排序）
order: 如果数组包含字段，则是要排序的字段

numpy.argsort() 函数返回的是数组值从小到大的索引值。


numpy.argmax() 
numpy.argmin()函数分别沿给定轴返回最大和最小元素的索引。


numpy.nonzero() 函数返回输入数组中非零元素的索引。

numpy.where() 函数返回输入数组中满足给定条件的元素的索引。

a = np.arange(10)

np.where(a < 5, a, 10*a)

# array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

ex. 

a = np.array([[0, 1, 2], [0, 2, 4], [0, 3, 6]])
np.where(a < 4, a, -1)  # -1 is broadcast


# array([[0, 1, 2], [0, 2, -1], [0, 3, -1]])
# 满足条件就返回a中对应的值，不满足条件就返回定义的广播值

numpy.extract() 函数根据某个条件从数组中抽取元素，返回满条件的元素。


x = np.arange(9.).reshape(3,  3)  

condition = np.mod(x,2)  ==  0  

np.extract(condition, x)  # <=====> x[x % 2 == 0]  <=====> x[np.mod(x,2)  ==  0 ]

# [0., 2., 4., 6., 8.]

## NumPy 矩阵库(Matrix)

In [ ]:
NumPy 中包含了一个矩阵库 numpy.matlib，该模块中的函数返回的是一个矩阵，
1. 转置 np.transpose(); A.T

2. np.zeros(), np.ones(), np.eye()

## NumPy 线性代数

### dot

In [ ]:
1. dot	两个数组的点积，即元素对应相乘。

a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(np.dot(a,b))  # [[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]

### vdot

In [ ]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
 
# vdot 将数组展开计算内积  1*11 + 2*12 + 3*13 + 4*14 = 130
print (np.vdot(a,b))

### inner, matmul, det, solve, inv

In [ ]:
3. inner	两个数组的内积
numpy.inner() 函数返回一维数组的向量内积。对于更高的维度，它返回最后一个轴上的和的乘积。



4. matmul	两个数组的矩阵积


5. determinant	数组的行列式

numpy.linalg.det() 函数计算输入矩阵的行列式。


6. solve	求解线性矩阵方程

numpy.linalg.solve() 函数给出了矩阵形式的线性方程的解。

7. inv	计算矩阵的乘法逆矩阵


import numpy as np 
 
a = np.array([[1,1,1],[0,2,5],[2,5,-1]]) 
 
print ('数组 a：')
print (a)
ainv = np.linalg.inv(a) 
 
print ('a 的逆：')
print (ainv)
 
print ('矩阵 b：')
b = np.array([[6],[-4],[27]]) 
print (b)
 
print ('计算：A^(-1)B：')
x = np.linalg.solve(a,b) 
print (x)
# 这就是线性方向 x = 5, y = 3, z = -2 的解

## NumPy IO

Numpy 可以读写磁盘上的文本数据或二进制数据。

NumPy 为 ndarray 对象引入了一个简单的文件格式：npy。

npy 文件用于存储重建 ndarray 所需的数据、图形、dtype 和其他信息。

常用的 IO 函数有：

load() 和 save() 函数是读写文件数组数据的两个主要函数，默认情况下，数组是以未压缩的原始二进制格式保存在扩展名为 .npy 的文件中。
savez() 函数用于将多个数组写入文件，默认情况下，数组是以未压缩的原始二进制格式保存在扩展名为 .npz 的文件中。
loadtxt() 和 savetxt() 函数处理正常的文本文件(.txt 等)

### np.save()

In [ ]:
numpy.save() 函数将数组保存到以 .npy 为扩展名的文件中。
参数说明：

file：要保存的文件，扩展名为 .npy，如果文件路径末尾没有扩展名 .npy，该扩展名会被自动加上。
arr: 要保存的数组
allow_pickle: 可选，布尔值，允许使用 Python pickles 保存对象数组，Python 中的 pickle 用于在保存到磁盘文件或从磁盘文件读取之前，对对象进行序列化和反序列化。
fix_imports: 可选，为了方便 Pyhton2 中读取 Python3 保存的数据。


ex. 
import numpy as np 
 
a = np.array([1,2,3,4,5]) 
 
# 保存到 outfile.npy 文件上
np.save('outfile.npy',a) 
 
# 保存到 outfile2.npy 文件上，如果文件路径末尾没有扩展名 .npy，该扩展名会被自动加上
np.save('outfile2',a)

### np.load()

In [ ]:
2. 可以看出文件是乱码的，因为它们是 Numpy 专用的二进制格式后的数据。

我们可以使用 load() 函数来读取数据就可以正常显示了：

import numpy as np 
 
b = np.load('outfile.npy')  
print (b)

### np.savez

In [ ]:
3.  np.savez
numpy.savez() 函数将多个数组保存到以 npz 为扩展名的文件中。

numpy.savez(file, *args, **kwds)
参数说明：

file：要保存的文件，扩展名为 .npz，如果文件路径末尾没有扩展名 .npz，该扩展名会被自动加上。
args: 要保存的数组，可以使用关键字参数为数组起一个名字，非关键字参数传递的数组会自动起名为 arr_0, arr_1, …　。
kwds: 要保存的数组使用关键字名称。
实例
import numpy as np 
 
a = np.array([[1,2,3],[4,5,6]])
b = np.arange(0, 1.0, 0.1)
c = np.sin(b)
# c 使用了关键字参数 sin_array
np.savez("runoob.npz", a, b, sin_array = c)
r = np.load("runoob.npz")  
print(r.files) # 查看各个数组名称
print(r["arr_0"]) # 数组 a
print(r["arr_1"]) # 数组 b
print(r["sin_array"]) # 数组 c

### savetxt()

In [ ]:
savetxt() 函数是以简单的文本文件格式存储数据，对应的使用 loadtxt() 函数来获取数据。

np.loadtxt(FILENAME, dtype=int, delimiter=' ')
np.savetxt(FILENAME, a, fmt="%d", delimiter=",")
参数 delimiter 可以指定各种分隔符、针对特定列的转换器函数、需要跳过的行数等。

实例
import numpy as np 
 
a = np.array([1,2,3,4,5]) 
np.savetxt('out.txt',a) 
b = np.loadtxt('out.txt')  
 
print(b)

## 作图

In [ ]:

16. 作图
'-'	实线样式
'--'	短横线样式
'-.'	点划线样式
':'	虚线样式
'.'	点标记
','	像素标记
'o'	圆标记
'v'	倒三角标记
'^'	正三角标记
'&lt;'	左三角标记
'&gt;'	右三角标记
'1'	下箭头标记
'2'	上箭头标记
'3'	左箭头标记
'4'	右箭头标记
's'	正方形标记
'p'	五边形标记
'*'	星形标记
'h'	六边形标记 1
'H'	六边形标记 2
'+'	加号标记
'x'	X 标记
'D'	菱形标记
'd'	窄菱形标记
'&#124;'	竖直线标记
'_'	水平线标记


’b'	蓝色
'g'	绿色
'r'	红色
'c'	青色
'm'	品红色
'y'	黄色
'k'	黑色
'w'	白色
"""


## 随机数np.random

[numpy.random用法](https://blog.csdn.net/weixin_42029738/article/details/81977492)

### rand均匀分布

In [ ]:
#  rand(d0, d1, ..., dn)  (0,1)内的均匀分布
np.random.rand?

In [ ]:
np.random.rand(1,20)

###  randn 标准正态分布

In [ ]:
# randn(d0, d1, ..., dn) 
# 返回标准正态分布 （0，1） （\mu,\sigma）
np.random.randn(1,2) 

### 生成多元正态分布multivariate_normal

In [ ]:

np.random.multivariate_normal(mean, cov[, size],) 

通过本函数可以返回一个或一组服从标准正态分布的随机样本值。   

# 生成shape为2*3*N的


### randint随机整数分布

In [ ]:
import numpy as np

c = np.random.randint(1e4) # 生成随机0到1e4的随机整数
c

### np.random.shuffle现场修改序列

In [ ]:
# 现场修改序列，改变自身内容。（类似洗牌，打乱顺序）
arr = np.arange(10)
np.random.shuffle(arr)
arr

### 排列

In [ ]:
# 返回一个随即排列
np.random.permutation(10)

### 从a中随机选择指定数据np.random.choice

In [ ]:
numpy.random.choice(a, size=None, replace=True, p=None)
通过本函数可以返回一个或一组服从标准正态分布的随机样本值。
#从a(只要是ndarray都可以，但必须是一维的)中随机抽取数字，并组成指定大小(size)的数组
#replace:True表示可以取相同数字，False表示不可以取相同数字
#数组p：与数组a相对应，表示取数组a中每个元素的概率，默认为选取每个元素的概率相同。

5.1 从0，1000中选择不重复的200个数字
theta_1 = np.random.choice(1000, 200, replace=False)
6. np.random.shuffle现场修改序列，改变自身内容。（类似洗牌，打乱顺序）
arr = np.arange(10)
np.random.shuffle(arr)
arr


## range等差数列

In [ ]:
# range(stop) -> range object
# range(start, stop[, step]) -> range object

range(0, 10, 3)  # 0,3,6,9


## np.linspace 等差数列 logspace

在python库numpy 中提供了函数linspace和logspace函数用于生产等差数列和等比数列。

    1.linspace函数生成等差数列

def linspace(<span class="mark">start, stop, num=50</span>, endpoint=True, retstep=False, dtype=None):

指定初始值、终止值、数量、是否包含终止值，默认为包含。

2.logspace函数生成等比数列

def logspace(<span class="burk">start, stop, num=50</span>, endpoint=True, base=10.0, dtype=None):

指定初始值、终止值、数量、是否包含终止值，默认为包含。

In [ ]:
import numpy as np

a = np.linspace(1,10,5,endpoint= True)
print(a) # [ 1.    3.25  5.5   7.75 10.  ]

b = np.linspace(1,10,5,endpoint= False)
print(b) #[1.  2.8 4.6 6.4 8.2]

c = np.linspace(1,10,5,retstep = False)
print(c) # [ 1.    3.25  5.5   7.75 10.  ]

d = np.linspace(1,10,5,retstep = True)
print(d) # (array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [ ]:
import numpy as np
# 等差数列

print(np.linspace(0.1, 1, 10, endpoint=True))
print(np.arange(0.1, 1.1, 0.1))
"""总结：
  arange 侧重点在于增量，不管产生多少个数
  linspace 侧重于num, 即要产生多少个元素，不在乎增量
"""
 
# 等比数列
np.logspace(1, 4, 4, endpoint=True, base=2) # 2**1---2**4

# lambdaMax.*[0 2.^(-10:2:0)];

## np.power([], [])，
 
 1. np.power(底数，指数)
 
 2. 底数和指数都要大于0

In [ ]:
import numpy as np
print(np.power(2,3))
#8

l = [1,2,3]
print(np.power(l,3))
#[ 1  8 27]

print(np.power(2,l))
#[2 4 8]

## 行列式，迹，秩，逆矩阵A

In [ ]:
print("原矩阵A：\n",A);
print("原矩阵b：\n",b);

A = np.random.rand(3,3)
print("转置矩阵A^T：\n",np.transpose(A)); # 转置
print("矩阵的行列式值|A|：\n",np.linalg.det(A)); # 方阵的行列式值：|A|
print("矩阵的迹trace(A)：\n",np.trace(A)); 
print("矩阵的秩rank(A)：\n",np.linalg.matrix_rank(A)); 
print("逆矩阵A^(-1)：\n",np.linalg.inv(A)); #矩阵的逆运算(条件：矩阵A可逆(行列式值不为0)| 矩阵A为方阵)

print("*"*30); # 分隔线

print("N阶单位矩阵:\n",np.eye(4));
print(np.zeros([5])); # 创建长为5的【一维】数组；[1,5]：创建第1行为5个元素的【二维】数组 

# 创建指定的初始化数组
print(np.array([1]))  # 生成 第1行含值为1的元素的【一维】数组
print(np.array([[56]])) # 生成 第1行含值为56的元素的【二维】数组
np.full((3,5),3.14) # 创建一个3x5的浮点型数组，数组的值都是3.14

##  矩阵计算
[矩阵计算 ](https://www.cnblogs.com/johnnyzen/p/10855208.html)

transpose, solve

In [ ]:
## 
A = [[2,1,2],
     [3,1,0],
     [1,1,-1]];
b = np.transpose(A)# 转置
# 求解未知参数矩阵X
X = np.linalg.solve(A,b) # 方式一：直接使用numpy的solve函数一键求解
#A_inv=np.linalg.inv(A) # 方式二：先求逆运算，再点积求值
#X=np.dot(A_inv,b) # a.dot(b) 与 np.dot(a,b) 效果相同；but np.dot(a,b)与np.dot(b,a)效果肯定是不同的(线性代数/矩阵常识)
print("方程组的解：\n",X);

## 向量、矩阵切片性质

向量的numpy 可以是矩阵的行，也可以按列操作

In [ ]:
d = np.zeros((2,1))
d1 = np.zeros(2)
d2 = np.array([[1,2],[3,4]])
d, d[0], d[1], d1, d1[0],d1[1],d2,d2[0],d2[1]  # 矩阵取一个坐标值是整行值，向量是列值

## numpy广播函数

[numpy广播函数](douban.com/note/713454002/)

In [ ]:
c = np.arange(10).reshape((2,5))
c1 = [1,2,3,4,5]
c*c1  
# array([[ 0,  2,  6, 12, 20],
#       [ 5, 12, 21, 32, 45]])



## 符号函数np.sign

In [ ]:
#导入numpy库
import numpy as np
 
#输入数据
dataArr = [-0.2, -1.1, 0, 2.3, 4.5, 0.0]
print("输入数据为：")
print(dataArr)
 
#使用numpy的sign(x)函数求输入数据的符号
signResult = np.sign(dataArr)
 
#打印出sign()的输出结果
print("\n使用sign函数的输出符号为：")
print(signResult)

## np.max, np.maximum, np.dot

In [ ]:
#1. 按行比较数据的大小，返回大的值
# np.max?
a = np.arange(4).reshape((2,2)) 

# np.max(df1, axis=None, out=None, keepdims=False)  
np.max(a)                # 3, 总体最大
np.max(a,axis=0)         #array([2, 3]) 安列
np.max(a,axis=1)         #array([1, 3]) 安行

# 按列实现最大值的筛选, 两个矩阵
# 例1
np.random.seed(1234)
df1=np.random.rand(2,3)
df2=np.random.rand(2,3)
np.maximum(df1,df2)
                    # array([[0.27646426, 0.80187218, 0.95813935],
                    #        [0.87593263, 0.77997581, 0.50099513]])

# 例1
np.random.seed(1111)
df3=np.random.rand(2,3)
np.maximum(0, df3)
                    # array([[0.0955492 , 0.9250037 , 0.34357342],
                    #        [0.31047694, 0.00200984, 0.23559472]])
        
# 两个列矩阵可以进行矩阵乘法吗？
c1 = np.array([2,3,4])
print(c1.shape)       # (3,)
print(c1.T.shape)     # (3,)
c2 = np.array([2,3,4])  
c3 = np.array([[2,3,4],[2,3,4],[2,3,4]])  
np.dot(c1,c2)         # 29
np.dot(c1,c3)         # [18, 27, 36]


In [ ]:
def l1_project(bplus, u):
    bnew = np.sign(bplus)*np.maximum(np.abs(bplus)-u,0)
    return bnew

d = np.array([-2,-1,-0,1,2])
l1_project(d,1)

## 保存数据np.savez,np.load

In [ ]:
# pandas的Dataframe

# 保存为np类型数据 https://www.jb51.net/article/143411.htm
# https://www.cnblogs.com/djdjdj123/p/12215528.html
import pandas as pd
import numpy as np
A = [1, 2, 3, 4]
B = [[2, 3, 4, 5], [1, 2, 3, 4]]
AB = pd.DataFrame([A, B, A, B])
ABC = ['A', 'B', 'C', 'D']

np.savez('exe1', D = A, B = B, AB = AB, ABC = ABC)

c = np.load('exe1.npz')

c['D']  # array([1, 2, 3, 4])

## np.linalg

### np.linalg.svd奇异值分解


In [ ]:
data = np.random.randn(3,4)
u,sigma,vt=np.linalg.svd(data)
sigma

## np.eye

In [ ]:
函数的原型：numpy.eye(N,M=None,k=0,dtype=<class 'float'>,order='C)

返回的是一个二维2的数组(N,M)，对角线的地方为1，其余的地方为0.
参数介绍：
（1）N:int型，表示的是输出的行数
（2）M：int型，可选项，输出的列数，如果没有就默认为N
（3）k：int型，可选项，对角线的下标，默认为0表示的是主对角线，负数表示的是低对角，正数表示的是高对角。
（4）dtype：数据的类型，可选项，返回的数据的数据类型
（5）order：{‘C’，‘F'}，可选项，也就是输出的数组的形式是按照C语言的行优先’C'，还是按照Fortran形式的列优先‘F'存储在内存中.


In [ ]:
a=np.eye(3)
a=np.eye(4,k=1)


## np.zeros

In [ ]:
5. np.zeros(shape, dtype=float, order='C')
用法：zeros(shape, dtype=float, order='C')
返回：返回来一个给定形状和类型的用0填充的数组；
参数：shape:形状
dtype:数据类型，可选参数，默认numpy.float64
dtype类型：
t ,位域,如t4代表4位
b,布尔值，true or false
i,整数,如i8(64位）
u,无符号整数，u8(64位）
f,浮点数，f8（64位）
c,浮点负数，
o,对象，
s,a，字符串，s24
u,unicode,u24
order:可选参数，c代表与c语言类似，行优先；F代表列优先




In [ ]:
np.zeros((2,3), dtype = np.float)

## np 浅拷贝和深拷贝

np.copy()属于深拷贝,拷贝前的地址和拷贝后的地址不一样. 而 " = " 属于浅拷贝,拷贝后的地址和拷贝前的地址一样.

In [ ]:
import numpy as np

# 改变 b 的值, a 的值会变, 但是改变 c 的值, a 的值不会变

a = np.ones((2,2))
b = a
c = a.copy()
print("id of a:", id(a))
print("id of b:", id(b))
print("id of c:", id(c))
b = 2.复习基础知识.ipynb
c = 23

print("id of a:", id(a),a)
print("id of b:", id(b), b)
print("id of c:", id(c))

## np.mean的用法

In [ ]:
import numpy as np
np.mean?

In [ ]:
# jupyter显示所有不同行输出变量
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" 

#Examples
a = np.array([[1, 2], [3, 4]])
a
np.mean(a)   # 总均值
np.mean(a, axis=0)  # 列均值
np.mean(a, axis=1) # 行均值


## np.sum()

In [ ]:
#Examples
a = np.array([[1, 2], [3, 4]])
a
np.sum(a)   # 总和
np.sum(a, axis=0)  # 列和
np.sum(a, axis=1) # 行和

# pandas

## pandas 基础知识

In [ ]:
path1 = '/Users/snszz/Documents/python/new_practice/file1/part_basic_location.csv'

data_location = pd.read_csv(path1)

data_location.head()   # tail(),  

# 如果希望显示出所有的列，我们可以通过简单的设置强制显示所有列。
# 为显示全部的列，添加如下的命令。
# pd.set_option('display.max_columns',None)

# data.tail(), data.head()

data_location.head(2)

#  查看

data_location.shape
# 列
data_location.columns
'''--------------------------------------------------------------------'''

# 4.简单统计
data_location.info()
data_location.describe()

# data_location.describe().iloc[:,:5]
# data_location.describe(include='all').iloc[:,:5]
'''--------------------------------------------------------------------'''

# Series 的唯一值个数 value_counts
 # data_location['type'].value_counts()
'''--------------------------------------------------------------------'''

#5. 数据筛选
 # selected_data = data[["gradyear","gender","age","friends"]]

 df.loc[(df['Education']=='Not Graduate') & (df['Loan_Status']=='Y') & (df['Gen
der']=='Female'),['Education','Loan_Status','Gender'] ]
'''--------------------------------------------------------------------'''

# 6 数据分组
# grouped_data = data.groupby("gradyear")
# grouped_data["age"].mean()

'''--------------------------------------------------------------------'''

# loan_data.sample(5)# 随机采样观察样本

'''--------------------------------------------------------------------'''

# 中等数量级数据读写及操作 chunksize

'''--------------------------------------------------------------------'''

# 用字典的方式指定某一列的特定值为缺失NaN，使得能够识别
map_id = {'grade':'A'}
loan_A_miss = pd.read_csv('./input/loandata.csv',na_values=map_id)

'''--------------------------------------------------------------------'''

# 6个账户以下为A级，6-12个账户为B级，12-18个账户为C级，18-24个账户为D级
bins = [0, 6, 12, 18, 24]
new_loan_data = pd.read_csv('./input/loandata.csv')
group_names = ['A', 'B', 'C', 'D']
loan_data['categories'] = pd.cut(new_loan_data['open_acc'], bins, labels=group
_names)
loan_data[:5]
'''--------------------------------------------------------------------'''

# 等频离散化
cuts = pd.qcut(amnt_series,4,labels=['a','b','c','d'])
cuts.value_counts()

'''--------------------------------------------------------------------'''
# 3.7 缺失值填补与离群值处理
#3.7.1 查看数据集的各个属性是否存在缺失值，并统计缺失值数量

loan_data.isnull().any() # 存在缺失值的列是那些

np.sum(loan_data.isnull(), axis=0) # 统计每一行缺失值的数量

loan_data[loan_data.isnull().values == True] # 展示存在缺失值的行
'''--------------------------------------------------------------------'''
3.7.2 删除缺失值

# 舍弃缺失值 dropna 并指定方法 how
loan_data_miss.dropna(how='any',axis=0)
                                                                           
# 在原DataFrame上做更改
loan_data_miss.dropna(how='any',inplace=True)

                                                                           
'''--------------------------------------------------------------------'''
3.7.3 填补缺失值

# 填充缺失值 fillna
# 通过字典指定每一列的填充方式
loan_data_fill = loan_data.fillna({'loan_amnt':'缺失值','annual_inc':'缺失
值'})


3.7.3.1 填补缺失值
fillna() 可以一次性解决缺失问题，该函数通过整列平均数/众数/中位数来填补该列的缺
失值。根据之前学到的 apply() 函数，观测到部分变量存在较多缺失，现在我们使用众数
来填补Gender、Married和Self_Employed三个变量的缺失值。代码如下：
mean_val = loan_data['annual_inc'].mean()
loan_data['annual_inc'] = loan_data['annual_inc'].fillna(mean_val)
                                   
'''--------------------------------------------------------------------'''                               
#导入mode判断众数
from scipy.stats import mode
print mode(df['Gender'])#查看Gender的众数

                                   
输出返回了Gender列的众数及其出现次数。注意，众数可以是个数组，因为高频的值可以
有多个。我们通常默认使用第一个： mode(data['Gender']).mode[0] ，其值为Male。
mode(df['Gender']).mode[0]


#缺失值填补
df['Gender'].fillna(mode(df['Gender']).mode[0],inplace=True)#inplace=True意味
着在原数据集上进行填补
df['Married'].fillna(mode(df['Married']).mode[0],inplace=True)
df['Self_Employed'].fillna(mode(df['Self_Employed']).mode[0],inplace=True)
#填补“Gender”、“Married”和“Self_Employed”三个变量后，再次调用num_missing

#创建计算缺失值函数
def num_missing(x):
    return sum(x.isnull())
                                   
函数查看列缺失情况
                                   
print df.apply(num_missing,axis = 0)
                                   
'''--------------------------------------------------------------------'''
# 3.7.4 离群值处理
loan_data.describe().astype(np.int64).T




'''--------------------------------------------------------------------'''
# 统计方法检测离群值

                                   
pct_25 = np.percentile(loan_data['loan_amnt'], 25)
pct_75 = np.percentile(loan_data['loan_amnt'], 75)
iqr = pct_75-pct_25
max_obser = pct_75+1.5*iqr
min_obser = pct_25-1.5*iqr


loan_data[loan_data['loan_amnt'] > max_obser]
                                   
loan_data[loan_data['loan_amnt'] < min_obser]
'''--------------------------------------------------------------------'''

# 3.8 数据融合和分组
# 产生两个数据框
                                   
df1 = loan_data[['home_ownership', 'grade']]
df2 = loan_data[['loan_amnt', 'grade']]
df1 = df1.sample(n=5).reset_index(drop=True)
df2 = df2.sample(n=3).reset_index(drop=True)
                                   

df_inner = pd.merge(df1, df2) # 默认内连接inner
print (df_inner)

'''--------------------------------------------------------------------'''
# 3.8—— 多重索引


#只在含缺失值的行中进行迭代
for i,row in df.loc[df['LoanAmount'].isnull(),:].iterrows():
ind = tuple([row['Gender'],row['Married'],row['Self_Employed']])#将Gende
r”、“Married”和“Self_Employed”三个变量值转为元组格式
df.loc[i,'LoanAmount'] = impute_grps.loc[ind].values[0]
#再次检查缺失值情况
print df.apply(num_missing,axis = 0)



#1. 多重索引需要在 loc 中用到定义分组group的元组(tuple)。这个元组会在函数中使
用。
#2. 需要使用 .values[0] 后缀。因为默认情况下元素返回的顺序与原数据库不匹
配。在这种情况下，直接指派会返回错误。

'''--------------------------------------------------------------------'''
思想： GroupBy = Split + apply + combine

grouped = loan_data.groupby('home_ownership')
grouped['annual_inc'].median() # 以上代码的语法糖

'''--------------------------------------------------------------------'''
3.9 透视表
                                   
loan_data.pivot_table(values='loan_amnt',
                    index=['home_ownership'],
                    columns=['grade', 'sub_grade'],
                    aggfunc='mean')# 与电子表格类似

#定义透视表
impute_grps = df.pivot_table(values = ['LoanAmount'],index = ['Gender','Marrie
d','Self_Employed'],aggfunc = np.mean)
print impute_grps

                                                              
'''--------------------------------------------------------------------'''
3.10 One-Hot编码

dummies = pd.get_dummies(loan_data['grade'],prefix='grade')
loan_data_dummies = pd.concat([loan_data,dummies],axis=1) # 拼接回原来的数据结
构 
print(loan_data_dummies.head(5))

'''--------------------------------------------------------------------'''

3.11 构建组合特征
loan_data['amnt_multi_acc'] = map(lambda x,y:x*y, loan_data['loan_amnt'],loan
_data['open_acc'])
                               
loan_numerical_poly = loan_data.select_dtypes(include=['int','float'])
print (loan_numerical_poly.head(5))

'''--------------------------------------------------------------------'''
"""
练习：对所有的名义型特征进行One-Hot编码，并将特征按照两两组合相乘(不包括自己与自
己)的方式产生组合特征，最后合并原始特征与组合特征
提示：
1. 将名义型特征和数值型特征进行分离，得到两个DataFrame loan_numerical 和
loan_object
2. 对所有名义型特征进行one-Hot编码，得到 dummies
3. 将数值型特征与编码后的进行轴向连接得到 loan_encoded
4. 对所有列循环两两相乘，产生组合特征，最后得到 loan_multiply
5. 将原始特征与组合特征进行轴向连接，得到最终可以用于构建模型 loan_final
"""


# 先做一些简单的预处理
loan_data = pd.read_csv('./input/loandata.csv')
loan_data['loan_status'] = loan_data['loan_status'].map(str.strip)
loan_data['loan_status'] = loan_data['loan_status'].map(str.title)
loan_data.drop(['issue_d', 'open_acc', 'sub_grade'], axis=1, inplace=True)
loan_data.dropna(inplace=True)

 # 分离名义型特征和数值型特征
loan_numerical = loan_data.select_dtypes(exclude=['object'])
loan_object = loan_data.select_dtypes(include=['object'])


# 对名义型特征进行one-hot编码
dummies = pd.get_dummies(loan_object)
# 轴向连接
loan_encoded = pd.concat([loan_numerical, dummies], axis=1)

# 交叉相乘得到组合特征
columns = list(loan_encoded.columns)
length = len(columns)
loan_multiply = pd.DataFrame()
for idx1, col1 in enumerate(columns)


'''--------------------------------------------------------------------'''

In [ ]:
14 pandas 复习
import pandas as pd
1. 
pd.Series(
    data=None,
    index=None,
    dtype=None,
    name=None,
    copy=False,
    fastpath=False,
)

a = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
a

2. 
pd.DataFrame(
    data=None,
    index=None,
    columns=None,
    dtype=None,
    copy=False,
)

# 列添加
data = pd.DataFrame() 
data['one'] = [1,2,3]

# 列删除
del data['one']

# 行选择，添加和删除
data.loc[]  # 索引
data.iloc[] # 整数位置传递
data

# 添加行append
import pandas as pd

df = pd.DataFrame([[1, 2], [3, 4]], columns = ['a','b'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns = ['a','b'])

df = df.append(df2)


# 删除行

df = df.drop(0)



序列基本功能
S.No.	属性或方法	描述
1	axes	返回行轴标签的列表。
2	dtype	返回对象的dtype。
3	empty	如果series为空，则返回True。
4	ndim	根据定义1返回基础数据的维度数。
5	size	返回基础数据中元素的数量。
6	values	将该序列作为ndarray返回。
7	head()	返回前n行。
8	tail()	返回最后n行。

DataFrame基本功能
让我们现在了解DataFrame基本功能是什么。下表列出了DataFrame Basic功能中的重要属性或方法。

S.No.	属性或方法	描述
1	Ť	转置行和列。
2	axes	以行轴标签和列轴标签作为唯一成员返回列表。
3	dtypes	返回此对象中的dtypes。
4	empty	如果NDFrame完全为空[没有项目]，则为true; 如果任何轴的长度为0。
5	ndim	轴/阵列尺寸的数量。
6	shape	返回表示DataFrame维度的元组。
7	size	NDFrame中的元素数目。
8	values	NDFrame的Numpy表示。
9	head()	返回前n行。
10	tail()	返回最后n行。


S.No.	功能	描述
1	count()	非空观测值的数量
2	sum()	值的总和
3	mean()	价值的意义
4	median()	价值的中间值
5	mode()	价值观的模式
6	std()	价值观的标准差
7	min()	最小值
8	max()	最大值
9	abs()	绝对值
10	prod()	价值的产物
11	cumsum()	累计和
12	cumprod()	累积产品


## 删除某一个特征的所有数据


In [ ]:
a = [1,2,3]
b1=a[0]
b2 = a[-1]
a.insert(0,a[0])
a.insert(-1,a[-1])
"""----------------------------------------------------------------------"""

# 删除某一个特征的所有数据

# pandas 删除全是女生的行 

import pandas as pd
df = pd.DataFrame({"key":['green','red', 'blue'],
            "data1":['a','b','c'],"sorce": [33,61,99]})
print(df)
print("---------------")

data1 = pd.concat([df,df],ignore_index=True)

data2=data1[-data1.sorce.isin([61])]


"""----------------------------------------------------------------------"""



## 导入的包

In [ ]:
import datetime
import numpy as np
import pandas as pd
from geopy.distance import geodesic
from collections import defaultdict,OrderedDict
import matplotlib.pyplot as plt
import dateutil
import warnings

warnings.filterwarnings('ignore')
# %matplotlib inline

# 这个是mac的画图中文乱码，window的可能不太一样
# 画图中文错误
# 用来正常显示中文标签
# window的画图中文乱码
# plt.rcParams['font.sans-serif'] = ['SimHei'] # 指定默认字体
# plt.rcParams['axes.unicode_minus'] = False # 解决保存图像是负号'-'显示为方块的问题

plt.rcParams['font.sans-serif'] = ['Arial Unicode Ms']
# 用来正常显示负号
plt.rcParams['axes.unicode_minus'] = False
# 可视化矩阵

# ————————————————————————————————————————————————————————————————————————————————————————————



## list_dict_Series

In [ ]:
"""
python 数据类型list、dict、numpy array、series、dataframe之间的转换\

https://blog.csdn.net/rosefun96/article/details/78970239


"""
"""---------------------------------------------------------------------------------------"""

#  1. list to others

import numpy as np
import pandas as pd
from pandas import Series, DataFrame


# list
data = [[2000, 'Ohino', 1.5],
        [2001, 'Ohino', 1.7],
        [2002, 'Ohino', 3.6],
        [2001, 'Nevada', 2.4],
        [2002, 'Nevada', 2.9]]  # type(data) 为 list

# list to series
ser = Series(data, index = ['one', 'two', 'three', 'four', 'five'])

# list to dataframe
df = DataFrame(data, index = ['one', 'two', 'three', 'four', 'five'], columns = ['year', 'state', 'pop'])

# list to array
ndarray = np.array(data)

"""---------------------------------------------------------------------------------"""

# 2. ndarray to others

# array to dataframe
pd = DataFrame(ndarray, index = ['one', 'two', 'three', 'four', 
'five'], 
columns = ['year', 'state', 'pop'])

# ndarray to list
mylist = ndarray.tolist()

"""---------------------------------------------------------------------------------------"""

# 3. dict to others

import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# dict
data = { 'name': ['Li', 'Zhang', 'Wang'],
         'year': [2000, 2001, 2002]}  # type(data) 为 dict

# dict to series
# 若不指定 index，data 的 key 充当 Series 的 index
ser = Series(data)
print('ser\n', ser)

# dict to dataframe
# 若不指定 columns，data 的 key 充当 DataFrame 的 columns
df = DataFrame(data)
print('df\n', df)

"""---------------------------------------------------------------------------------------"""

# 4. Series to others

# 如果把DataFrame取一列就是Series格式了。

# series to np array

# 需要pandas version 0.24以上
arr = ser.to_numpy()
# 或者
arr = np.array(ser)
# Series转换成dict
dt = ser.to_dict()

"""---------------------------------------------------------------------------------------"""

# 5. DataFrame to others
# dataframe
data = DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['a', 'b', 'c'])
print(data)

# dataframe to array
arr = data.values
print('arr\n', arr)
print(type(arr))

# dataframe to dict 
dict = data.to_dict()
print(dict)

"""
#  DataFrame.to_dict(self, orient='dict', into=<class 'dict'>) 还可以转换成 list,series等：

 orient : str {‘dict’, ‘list’, ‘series’, ‘split’, ‘records’, ‘index’}
Determines the type of the values of the dictionary.

‘dict’ (default) : dict like {column -> {index -> value}}
‘list’ : dict like {column -> [values]}
‘series’ : dict like {column -> Series(values)}
‘split’ : dict like {‘index’ -> [index], ‘columns’ -> [columns], ‘data’ -> [values]}
‘records’ : list like [{column -> value}, … , {column -> value}]
‘index’ : dict like {index -> {column -> value}}
Abbreviations are allowed. s indicates series and sp indicates split.

"""

"""---------------------------------------------------------------------------------------"""



## merge数据合并

In [ ]:
# merge数据合并
"""
https://zhuanlan.zhihu.com/p/102274476

上面的引入部分说到merge是用来拼接两张表的，那么拼接时自然就需要将用户信息一一对应地进行拼接，
所以进行拼接的两张表需要有一个共同的识别用户的键（key）。总结来说，整个merge的过程就是将信息
一一对应匹配的过程，下面介绍merge的四种类型，分别为'inner'、'left'、'right'和'outer'。

一、inner
merge的'inner'的类型称为内连接，它在拼接的过程中会取两张表的键（key）的交集进行拼接。

二、left 和right
'left'和'right'的merge方式其实是类似的，分别被称为左连接和右连接。这两种方法是可以互相转换的，所以在这里放在一起介绍。

'left'
merge时，以左边表格的键为基准进行配对，如果左边表格中的键在右边不存在，则用缺失值NaN填充。


'right'
merge时，以右边表格的键为基准进行配对，如果右边表格中的键在左边不存在，则用缺失值NaN填充。

三、outer

'outer'是外连接，在拼接的过程中它会取两张表的键（key）的并集进行拼接


"""

# 1.现在用'inner'的方式进行merge

df_1 = pd.DataFrame({'age':[23, 46, 32, 19], 'useid':['a','b','c','d']})
df_2 = pd.DataFrame({'payment':[2000, 3500], "useid":['a','b']})

df_1.merge(df_2,how='inner',on='useid')  # 你有我有的useid, 交集


# 2. left
df_1.merge(df_2,how='left',on='useid')  # 左边有的id 右边没有， 则 右边的补NAN  ②若右表中的payment列合并到左表中，对于没有匹配值的用缺失值NaN填充

#3.right

df_2.merge(df_1,how='right',on='useid') 
                  # 对于'right'类型的merge和'left'其实是差不多的，只要把两个表格的位置调换一下，两种方式返回的结果就是一样的（），如下：

# 4. outer


df_1 = pd.DataFrame({'age':[23, 46, 32, 19], 'useid':['a','b','c','d']})
df_2 = pd.DataFrame({'payment':[2000, 3500, 3000], "useid":['a','b','e']})

df_1.merge(df_2,how='outer',on='useid')


#  对于我们的原始数据，首先将车辆基础数据进行预处理留下合理数据， 将GPS基础数据与车辆基础数据进行拼接，使用”inner“,拼接就可以了


## groupby

In [ ]:
# Pandas数据处理三板斧——map、apply、applymap详解

boolean=[True,False]
gender=["男","女"]
color=["white","black","yellow"]
data_d1=pd.DataFrame({
    "height":np.random.randint(150,190,100),
    "weight":np.random.randint(40,90,100),
    "smoker":[boolean[x] for x in np.random.randint(0,2,100)],
    "gender":[gender[x] for x in np.random.randint(0,2,100)],
    "age":np.random.randint(15,90,100),
    "color":[color[x] for x in np.random.randint(0,len(color),100) ]
}
)

"""
1. map用法
如果需要把数据集中gender列的男替换为1，女替换为0，怎么做呢？绝对不是用for循环实现，
使用Series.map()可以很容易做到，最少仅需一行代码。
"""
# ①使用字典进行映射
data_d1['gender'] = data_d1['gender'].map({"男":1, "女": 0})

#②使用函数
def gender_map(x):
    gender = 1 if x == "男" else 0
    return gender
#注意这里传入的是函数名，不带括号
data["gender"] = data["gender"].map(gender_map)

"""
不论是利用字典还是函数进行映射，map方法都是把对应的数据逐个当作参数传入到字典或函数中，得到映射后的值。
"""

"""-----------------------------------------------------------------------------------------------"""

# 2. apply, 

# https://zhuanlan.zhihu.com/p/100064394

def apply_age(x,bias):
    return x+bias

#以元组的方式传入额外的参数

data["age"] = data["age"].apply(apply_age,args=(-3,))  #  可以看到age列都减了3

# 总而言之，对于Series而言，map可以解决绝大多数的数据处理需求，但如果需要使用较为复杂的函数，则需要用到apply方法。

# 沿着0轴求和
data[["height","weight","age"]].apply(np.sum, axis=0)  # 列和

# 沿着0轴取对数
data[["height","weight","age"]].apply(np.log, axis=0)  # 列和


# 行和

def BMI(series):
    weight = series["weight"]
    height = series["height"]/100
    BMI = weight/height**2
    return BMI

data["BMI"] = data.apply(BMI,axis=1)

"""-----------------------------------------------------------------------------------------------"""

# 3. applymap

data_df = pd.DataFrame(
    {
        "A":np.random.randn(5),
        "B":np.random.randn(5),
        "C":np.random.randn(5),
        "D":np.random.randn(5),
        "E":np.random.randn(5),
    }
)

# 将DataFrame中所有的值保留两位小数显示

data_df.applymap(lambda x:"%.2f" % x)




day = [data_lo.time.iloc[i].date().strftime('%Y-%m-%d') for i in range(len(data_lo))]  # 把time 转换有y_m_d的字符串类型

data_lo['day'] = day  # 把 day 加入到 data_lo数据集

data_lo.to_csv('data_location_del_less_10.csv', index=None)  # 保存数据

d1 = data_lo.groupby("ID")["day"].value_counts()  # 按ID对数据进行分组，在每个ID中按day统计个数， 知道每个ID下一共有多少天的数据，每天的数据量是多少

d1.to_csv('day_counts_point.csv')  # 保存id下每天的记录

d1 = pd.read_csv('day_counts_point.csv', index_col=None)  # 读取数据

d2 = d1.groupby("ID")["count"].agg(['max','min','mean','count','sum', 'median','std','var'])  # 使用 agg将多个函数功能合并展示

#  https://zhuanlan.zhihu.com/p/101284491?utm_source=wechat_session

# pandas 分组操作groupby, agg, transform, 

#  实现分组操作的代码很简单，
company=["A","B","C"]
cd = ['D', 'E','F']
df = pd.DataFrame({
    "company":[company[x] for x in np.random.randint(0,len(company),10)],
    'cd':[cd[x] for x in np.random.randint(0,len(company),10)],
    "salary":np.random.randint(5,50,10),
    "age":np.random.randint(15,50,10)
}
)


group = df.groupby('company')  # 将上面的数据集按照company字段进行划分

list(group)  # 这里把group转换成list的形式

# 如果想对针对不同的列求不同的值，比如要计算不同公司员工的平均年龄以及薪水的中位数，可以利用字典指定进行聚合操作：

df.groupby('company').agg({'salary':'median','age':'mean'})

"""
在上面的agg中，我们学会了如何求不同公司员工的平均薪水，如果现在需要在原数据集中新增一列avg_salary，
代表员工所在的公司的平均薪水（相同公司的员工具有一样的平均薪水），该怎么实现呢？如果按照正常的步骤来
计算，需要先求得不同公司的平均薪水，然后按照员工和公司的对应关系填充到对应的位置，不用transform的话，
实现代码如下：
"""
# https://blog.csdn.net/weixin_42028854/article/details/88829352?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-2.channel_param&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-2.channel_param

# pandas 转换为字典， orient:value的形式：“list”, "dist", "series", "split", "report", "index"

# df.to_dict(orient="list")

avg_salary_dict = df.groupby("company")['salary'].mean().to_dict()

df['avg_salary'] = df['company'].map(avg_salary_dict)  # 对company的列进行操作

# 可以直接用transform实现avg_salary_dict， 和map的功能

df['avg_salary1'] = df.groupby('company')['salary'].transform('mean')




# matplotlib

In [ ]:
import numpy as np
import matplotlib.pyplot as plt  # Python 绘图工具(业界推荐)

# 数据初始化
A = [
    [1,pow(-3,3)],
    [1,pow(-2,3)],
    [1,pow(-1,3)],
    [1,pow(2,3)],
    [1,pow(4,3)]
];

At =  np.transpose(A); # A的转置矩阵

y = np.transpose([14.3,8.3,4.7,8.3,22.7]);


# step1:求解
## 令 (a ,b)^T 为 未知参数X
X = np.dot(np.dot(np.linalg.inv(np.dot(At,A)),At),y)
print(X)
print("a:",X[0])
print("b:",X[1])

# step2:查看拟合效果
x = [-3,-2,-1,2,4];
## 1. 计算拟合数值 fitValue
def fitValue(arg_x):
    a = X[0];
    b = X[1];
    return a + b*pow(arg_x,3);

fitValues = np.zeros([5]); # 创建长为5的【一维】数组；[1,5]：创建第1行为5个元素的【二维】数组 
for i in range(0,len(fitValues)):
    fitValues[i] = fitValue(x[i]);
    print(i,":","x(i):",x[i],"fit Y:",fitValues[i]); # just for test
    pass;

## 2. 绘图可视化
yt = np.transpose(y); # y的转置
plt.rcParams['figure.dpi'] = 100 #分辨率
plt.scatter(x, yt, marker = '*',color = 'red', s = 10 ,label = 'Actual Dataset') # 真实数据集
plt.scatter(x, fitValues, marker = 'x',color = 'green', s = 10 ,label = 'Fitting Dataset') #[拟合数据集]
plt.legend(loc = 'best')    # 设置 图例所在的位置 使用推荐位置
plt.show() 

##  matplotlib 画子图

In [ ]:
from matplotlib import pyplot as plt
import numpy as np
x = np.linspace(1, 100, num= 25, endpoint = True)
def y_subplot(x,i):
    return np.cos(i * np.pi *x)
#使用subplots 画图
f, ax = plt.subplots(2,2)
#type(f) #matplotlib.figure.Figure

style_list = ["g+-", "r*-", "b.-", "yo-"]
ax[0][0].plot(x, y_subplot(x, 1), style_list[0])
ax[0][1].plot(x, y_subplot(x, 2), style_list[1])
ax[1][0].plot(x, y_subplot(x, 3), style_list[2])
ax[1][1].plot(x, y_subplot(x, 4), style_list[3])

plt.show()


In [ ]:
2. #使用subplot画图
for i in  range(1,5):
    plt.subplot(2,2,i)
    plt.plot(x, y_subplot(x,i), style_list[i- 1])
plt.show()


## 画图基础操作


In [ ]:
# 图名，图例，轴标签，轴边界，轴刻度，轴刻度标签等

df = pd.DataFrame(np.random.rand(10,2),columns=['A','B'])
fig = df.plot(figsize=(12, 6))
# figsize：创建图表窗口，设置窗口大小
# 创建图表对象，并赋值与fig

plt.title('Interesting Graph - Check it out')  # 图名
plt.xlabel('Plot Number')  # x轴标签
plt.ylabel('Important var') # y轴标签

plt.legend(loc = 'upper right')  
# 显示图例，loc表示位置
# 'best'         : 0, (only implemented for axes legends)(自适应方式)
# 'upper right'  : 1,
# 'upper left'   : 2,
# 'lower left'   : 3,
# 'lower right'  : 4,
# 'right'        : 5,
# 'center left'  : 6,
# 'center right' : 7,
# 'lower center' : 8,
# 'upper center' : 9,
# 'center'       : 10,

plt.xlim([0,12])  # x轴边界
plt.ylim([0,1.5])  # y轴边界
plt.xticks(range(10))  # 设置x刻度
plt.yticks([0,0.2,0.4,0.6,0.8,1.0,1.2])  # 设置y刻度
fig.set_xticklabels("%.1f" %i for i in range(10))  # x轴刻度标签 保留小数点后一位小数
fig.set_yticklabels("%.2f" %i for i in [0,0.2,0.4,0.6,0.8,1.0,1.2])  # y轴刻度标签 #保留小数点后2位小数
 # 范围只限定图表的长度，刻度则是决定显示的标尺 → 这里x轴范围是0-12，但刻度只是0-9，刻度标签使得其显示1位小数 # 轴标签则是显示刻度的标签 print(fig,type(fig)) # 查看表格本身的显示方式，以及类别
"""------------------------------------------------------------------------------------------------------------------------------------------------------------------------"""

# 2. 散点图

# 对于 id的个数画图，查看一下，id的数量分布
fig = plt.figure(figsize=(12, 8))

#新加入的代码如下：
# plt.xlabel("") #x轴说明
# plt.ylabel("id的计数") #y轴说明
plt.title("车辆的经纬度") #此图像的标题
plt.scatter(data_37532_1_03_del_33['gpsX'], data_37532_1_03_del_33['gpsY'])
plt.scatter(data_37532_1_03_del['gpsX'], data_37532_1_03_del['gpsY'], marker='*', color = 'red')
plt.show()

"""------------------------------------------------------------------------------------------------------------------------------------------------------------------------"""


# 3. 

# 对于 id的个数画图，查看一下，id的数量分布
fig = plt.figure(figsize=(12, 8))
data_37532_1_03_del_second = data_37532_1_03_del_33.loc[v_del[v_del[0] > 33.33].index]
#新加入的代码如下：
# plt.xlabel("") #x轴说明
# plt.ylabel("id的计数") #y轴说明
plt.title("车辆的经纬度") #此图像的标题
plt.scatter(data_37532_1_03_del_33['gpsX'], data_37532_1_03_del_33['gpsY'], alpha=0.1)
plt.scatter(data_37532_1_03_del['gpsX'], data_37532_1_03_del['gpsY'], marker='*', color = 'red')
plt.scatter(data_37532_1_03_del_second['gpsX'], data_37532_1_03_del_second['gpsY'], marker='*', color = 'red')
plt.show()


"""------------------------------------------------------------------------------------------------------------------------------------------------------------------------"""

# 4. 

# 对于 id的个数画图，查看一下，id的数量分布
fig = plt.figure(figsize=(12, 8))

#新加入的代码如下：
# plt.xlabel("") #x轴说明
# plt.ylabel("id的计数") #y轴说明
plt.title("车辆的经纬度") #此图像的标题
plt.scatter(data_37532_1_03_del_33_['gpsX'], data_37532_1_03_del_33_['gpsY'], alpha=0.1)
plt.scatter(data_37532_1_03_del['gpsX'], data_37532_1_03_del['gpsY'], marker='*', color = 'red')
plt.scatter(data_37532_1_03_del_second['gpsX'], data_37532_1_03_del_second['gpsY'], marker='*', color = 'green')
plt.show()

"""------------------------------------------------------------------------------------------------------------------------------------------------------------------------"""


## 中文出错

In [ ]:
# 这个是mac的画图中文乱码，window的可能不太一样
# 画图中文错误
# 用来正常显示中文标签
# window的画图中文乱码
# plt.rcParams['font.sans-serif'] = ['SimHei'] # 指定默认字体
# plt.rcParams['axes.unicode_minus'] = False # 解决保存图像是负号'-'显示为方块的问题

plt.rcParams['font.sans-serif'] = ['Arial Unicode Ms']
# 用来正常显示负号
plt.rcParams['axes.unicode_minus'] = False
# 可视化矩阵

# 时间相关数据操作

In [ ]:
# 时间序列
"""


内容目录

1. 基础概述
2. 转换时间戳
3. 生成时间戳范围
4. DatetimeIndex
5. DateOffset对象
6. 与时间序列相关的方法
6.1 移动
6.2 频率转换
6.3 重采样

一、基础概述
下面列出了 Pandas中 和时间日期相关常用的类以及创建方法。
类                 备注             创建方法
Timestamp        时刻数据            to_datetime，Timestamp
DatetimeIndex   Timestamp的索引      to_datetime，date_range，DatetimeIndex
Period           时期数据             Period
PeriodIndex   Period                 period_range， PeriodIndex
Pandas 中关于时间序列最常见的类型就是时间戳（Timestamp）了，创建时间戳的方法有很多种，我们分别来看一看。
"""
pd.Timestamp(2018,5,21)

pd.Timestamp('2018-5-21')

# 除了时间戳之外，另一个常见的结构是时间跨度（Period）

pd.Period("2018-01")

pd.Period("2018-05", freq="D")

#索引后会自动强制转为为 DatetimeIndex 和 PeriodIndex。

"""-------------------------------------------------------------------------------------"""

# 二、转换时间戳
#   通过 to_datetime 能快速将字符串转换为时间戳。当传递一个Series时，
#   它会返回一个Series（具有相同的索引），而类似列表的则转换为DatetimeIndex。

pd.to_datetime(pd.Series(["Jul 31, 2018", "2018-05-10", None]))

pd.to_datetime(["2005/11/23", "2010.12.31"])

#除了可以将文本数据转为时间戳外，还可以将 unix 时间转为时间戳

pd.to_datetime([1349720105, 1349806505, 1349892905], unit="s")

pd.to_datetime([1349720105100, 1349720105200, 1349720105300], unit="ms")

"""-------------------------------------------------------------------------------------"""

# 三、生成时间戳范围

pd.date_range("2018-6-26", periods=8)

pd.bdate_range("2018-6-26", periods=8)

#可以看出，date_range 默认使用的频率是 日历日，而 bdate_range 默认使用的频率是 营业日。当然了，我们可以自己指定频率，比如，我们可以按周来生成时间戳范围。
pd.date_range("2018-6-26", periods=8, freq="W")


"""-------------------------------------------------------------------------------------"""

# 四. DatetimeIndex
# DatetimeIndex 的主要作用是之一是用作 Pandas 对象的索引，使用它作为索引除了拥有普通索引对象的所
# 有基本功能外，还拥有简化频率处理的高级时间序列方法。

rng = pd.date_range("2018-6-24", periods=4, freq="W")
ts = pd.Series(range(len(rng)), index=rng)

# 通过日期访问数据
ts["2018-07-08"]

# 通过日期区间访问数据切片
ts["2018-07-08": "2018-07-22"]

#传入年份
ts["2018"]

# 传入年份和月份
ts["2018-07"]


#除了可以使用字符串对 DateTimeIndex 进行索引外，还可以使用 datetime（日期时间）对象来进行索引。
from datetime import datetime
ts[datetime(2018, 7, 8) : datetime(2018, 7, 22)]

# 获取年份
ts.index.year

# 获取星期几
ts.index.dayofweek

# 获取一年中的第几个星期
ts.index.weekofyear


"""-------------------------------------------------------------------------------------"""

# 六、与时间序列相关的方法

# 在做时间序列相关的工作时，经常要对时间做一些移动/滞后、频率转换、采样等相关操作，我们来看下这些操作如何使用吧。

"""-------------------------------------------------------------------------------------"""



In [ ]:
def fun_var_args(farg, *args):  
    print("arg:", farg)
    for value in args:  
        print("another arg:", value)  
        
fun_var_args(1, "two", 3) # *args可以当作可容纳多个变量组成的list 

In [ ]:
def fun_var_kwargs(farg, **kwargs):  
    print("arg:", farg) 
    for key in kwargs:  
        print("another keyword arg: %s: %s" % (key, kwargs[key]))

fun_var_kwargs(farg=1, myarg2="two", myarg3=3)   # myarg2和myarg3被视为key， 感觉**kwargs可以当作容纳多个key和value的dictionary  

In [ ]:
def fun_var_kwargs(farg, **kwargs):  
    s = fun1(**kwargs)
    print(fun1(**kwargs))

def fun1(**kwargs):
    if 'seed' not in list(kwargs.keys()):
        kwargs['seed'] = 1
    else:
        pass
    return  kwargs, kwargs.keys()

fun1(seed = 1)

#  字典

In [ ]:
11. 字典

tel = {'jack': 4098, 'sape': 4139}

tel.keys()  # dict_keys(['jack', 'sape'])

list(tel.keys())  # ['jack', 'sape']

tel.values()  # dict_values([4098, 4139])

'guido' in tel  # False

'guido' not in tel  # True

d = dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

d  # {'sape': 4139, 'guido': 4127, 'jack': 4098}

{x: x**2 for x in (2, 4, 6)}  # {2: 4, 4: 16, 6: 36}

# d.items()   enumerate() , zip(), reversed(),倒位 ；
# 使用 sorted() 函数，它不改动原序列，而是生成一个新的已排序的序列:

knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.items():
    print(k, v)

# in， not in
# is, not is
# and or not B


## 判断某个字典是否存在某个key

In [ ]:
dict1 = dict()
dict1['a'] = 0

# 判断某个字典是否存在某个key
if 'a' not in dict1:
    dict1['a'] = 1
else:
        print('a in exist in dict1')

# list

In [ ]:
 常用的复习
1字符串 + *
pre = "py"
pre + "thon"  #'python'
pre * 3  # pypypy
2 list 中的 +， *
a = [1, 2, 3]
a + a  # [1, 2, 3, 1, 2, 3]
a * 3  # [1, 2, 3, 1, 2, 3, 1, 2, 3]

 3. len(), append(), extend(),insert(i,x), remove(x) list.pop(i)
# list.clear(), index(x), count(x), sort(), reverse(), copy() = a[:]
#


# 元组

In [ ]:
10.  元组 （）， 集合 set(),
a0 = ('abracadabra')  # 'abracadabra'
a = set('abracadabra')  # {'a', 'b', 'c', 'd', 'r'}


# 集合 set()

# zip ,zip(*)

In [ ]:
"""
3 zip与zip(*)
>>> a = [1,2,3]
>>> b = [4,5,6]
>>> c = [4,5,6,7,8]
>>> zipped = zip(a,b)     # 打包为元组的列表
[(1, 4), (2, 5), (3, 6)]
>>> zip(a,c)              # 元素个数与最短的列表一致
[(1, 4), (2, 5), (3, 6)]
>>> zip(*zipped)          
# 与 zip 相反，可理解为解压，为zip的逆过程，可用于矩阵的转置
[(1, 2, 3), (4, 5, 6)]

"""

matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]

list(zip(*matrix))  # [(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

[[i, j] for i, j in zip(a, b)]  # [[1, 5], [2, 6], [3, 7], [4, 8]]


# enumerate()

In [ ]:
[[i, j] for i, j in enumerate(range(3))]  # [[0, 0], [1, 1], [2, 2]]

# 匿名函数 lambda 

In [ ]:
f = lambda a, b: a + b

f(2, 3)  # 5



# pass

In [ ]:
 pass:

# def f(arg): pass    # a function that does nothing (yet)
# class C: pass       # a class with no methods (yet)


# break

In [ ]:
 break 循环终止  continue: 结束本次循环，开始下一次

# 生成不连续对称区间的值# 

In [ ]:
def ini_x_(n=100,p=1000,k=20,seed=22):
    # 生成Z， W
    np.random.seed(seed)
    Z = np.random.randn(n, k)
    W = np.random.randn(n, p)
    E = 0.5 * np.random.randn(n, p) # 误差
    # 生成[0.5, 1.5]的均匀分布
    A = np.random.uniform(0.5, 1.5, (k,p))
    # 生成{0,1}随机均匀分布
    A1 = np.random.randint(0,2,(k,p))
    # A1==0的索引对应的A==-A
    for i,j in zip(np.where(A1==0)[0],np.where(A1==0)[1]):
        A[i,j] = - A[i,j] 

    # 生成b
    b = np.sqrt(k) * np.random.uniform(0.5, 1.5, (p,))
    # 生成{0,1}随机均匀分布
    b1 = np.random.randint(0,2,(p,))
    # b1==0的索引对应的b == -sqrt(k) * b
    for i in np.where(b1==0)[0]:
        b[i] = -1 * b[i] 
    
    return np.dot(Z,A) + W * b + E , b

# # np.linalg.norm与sum.sum(), A.sum()三者是等价的

In [ ]:
A = np.random.randint(0,100, (2,3))
A, np.linalg.norm(A)**2,sum(sum(A**2)), (A**2).sum()

#  objVals = np.zeros((20,1)), np.zeros(20)的·区别

In [ ]:
objVals1 = np.zeros((20,1))
objVals2 = np.zeros((20,))
objVals3 = np.zeros(20)
objVals1[0:20], objVals2[0:20], objVals3[0:20] 

# 精确度(Precision)、召回率(Recall)和F1_Score

在衡量模型性能好坏时，我们经常用到精确度、召回率和F1评分。

![](https://img-blog.csdn.net/20180906110246947?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3lfeGlhbnNoZW5n/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70)
如上表格所示，模型的最终预测结果可分为上述四类情况，假设我们现在是要预测队伍里的男生女生人数，男生为正例，女生为负例，则：

1. True Positive：正确的正例，即男生被正确分为男生
2. False Positive：错误的正例，即女生被错误分为男生
3. False Negative：错误的负例，即男生被错误分为女生
4. True Negative：正确的负例，即女生被正确分为女生

我们可以这样记忆，前面为True的就代表分类正确，False的就代表分类错误；后边是Positive的就是正例，后边是Negative的就是负例。

下面是精确度(Precision)、召回率(Recall)和F1_Score的公式：

![image.png](https://img-blog.csdn.net/20180906111249373?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3lfeGlhbnNoZW5n/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70)

由此我们可以得到以下规律：
假设模型分类取得了正例和负例的分类结果，那么Precision就是模型所得分类结果中，真正的正例与分类所得正例的比值，也可叫作查准率；Recall就是模型所得分类结果中，真正的正例与数据中实际真正正例的比值，也可叫做查全率；
在对模型进行评估的过程中，仅用精确度或者召回率去评估模型是无法全面评估模型优劣的，所以人们将精确度和召回率结合起来，得到了F1评分作为模型的实际评分准则，在多分类问题中，F1是精确度和召回率的调和平均：

![](https://img-blog.csdn.net/20180906112328707?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3lfeGlhbnNoZW5n/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70)

最后提一下所谓的准确率(Accuracy)，准确率就是分类任务中全部分类正确(不论正例负例)的总数与全体总数的比值，Accuracy = (TP + TN )/( TP + FP + TN + FN)。

#  $l_{1,2}范数计算$

In [ ]:
np.random.seed(22)
data2 = np.random.randn(3,4)
data3 = np.random.randn(4,1)
print("data2:\n",data2)
print("\n")
print("np.abs(data2).sum():\n", np.abs(data2).sum())
print("\n")
# l1范数是矩阵的时候，表示列和的最大值。表示向量的时候相等
print("np.linalg.norm(data2, ord=1):\n", np.linalg.norm(data2, ord=1))

# 向量时两个相等

np.abs(data3).sum() # 3.4545447620055505
np.linalg.norm(data3, ord=1)  # 3.4545447620055505


#  $L_2,L_1$范数

In [ ]:
import numpy as np
a = np.array([[complex(1,-1),3], [2,complex(1,1)]])
print(a)
print("矩阵2的范数")
print(np.linalg.norm(a, ord=2))   #计算矩阵2的范数
print("矩阵1的范数")
#计算矩阵1的范数
print(np.linalg.norm(a,ord=1) )
print("矩阵无穷的范数")
print(np.linalg.norm(a,ord=np.inf) )


# $L_{F}$范数

In [ ]:
# np.random.seed(222)
a = np.random.rand(4,4)
print(a)

print("****"*15)
print(a**2)

print("****"*15)
print(a*a)

print("****"*15)
print(a[0,0]*a[0,0])

print("****"*15)
print("a*a表示对应元素乘法，也是f范数的平方")
print(np.sqrt(sum(sum(a*a))))


print("****"*15)
print("f范数的平方")
print(np.linalg.norm(a))
print(np.linalg.norm(a, ord = 'fro'))

# 核范数

In [ ]:
b = np.random.rand(2,3)
print(b)
print("*****"*15)
print("核范数：")
print(np.linalg.norm(b, ord='nuc'))
print(sum(np.abs(b)))

# 矩阵f范数和直接求和的区别

![](https://img-blog.csdnimg.cn/2020112121564050.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80Mzk3NzY0MA==,size_16,color_FFFFFF,t_70#pic_center)

In [ ]:
np.random.seed(22)
data2 = np.random.randn(3,4)
data3 = np.random.randn(4,1)
print("data2:\n",data2)
print("\n")
print("np.abs(data2).sum():\n", np.abs(data2).sum())
print("\n")
# l1范数是矩阵的时候，表示列和的最大值。表示向量的时候相等
print("np.linalg.norm(data2, ord=1):\n", np.linalg.norm(data2, ord=1))

# 向量时两个相等

np.abs(data3).sum() # 3.4545447620055505
np.linalg.norm(data3, ord=1)  # 3.4545447620055505


# 求和的区别

In [ ]:
import numpy as np
np.random.seed(2)
d = np.random.rand(2,3)
sum(d)  # 列和  行向量等于列向量
d.sum()  # 所有元素之和 与sum(sum(d))等价

e = np.random.rand(1,3)
np.sum(e)   # 总和
np.sum(e,axis=0)  # 列和
np.sum(e, axis=1) # 行和

# lambda1*sum(sqrt(sum(A.^2,1)))
dd = np.ones((20,2))
lambda1 = 1
# lambda1*np.sum(np.sqrt(np.sum(dd**2,axis=0)))   # 耗时5ms
# lambda1*sum(np.sqrt(sum(dd**2)));               # 耗时6ms
# lambda1*(np.sqrt(np.sum(dd**2,axis=0))).sum()  # 耗时5ms


# sum

In [ ]:

np.random.seed(222)
c = np.random.randint(1,3,size=(2,3))
print(c)
print(sum(c))
print(np.sum(c, axis= 0))
print(np.sum(c, axis=1))
# 列和大于0的个数
print(sum(sum(c)>0))



#  Python和matlab的对应

[matlab和python对应函数](https://blog.csdn.net/panghaomingme/article/details/70308290)

# Python中的if __name__ == '__main__'

https://blog.csdn.net/qq_33254870/article/details/81668297

In [ ]:
"""
Python中的if __name__ == '__main__'  : 
写一个函数1的时候，在另一个函数2调用函数1时，只运行函数1的函数块，
不运行函数1中”测试块“，把测试块写在if __name__ == '__main__'  :之后

"""

# const.py
 
PI = 3.14
 
def train():
    print("PI:", PI)
train()

In [ ]:
def l2_pro_mex(Aplus, u,n):
    a = np.linalg.norm(Aplus, ord=n)
    Anew = Aplus * np.maximum(0, a-u)/a
    return Anew
if __name__ == '__main__':
    Aplus = np.random.rand(20,200)
    u = 0.1*np.ones((1,200))
    n = 2
    Anew = l2_pro_mex(Aplus, u,n)
    print(Anew)

In [ ]:
np.array([[2,3,4],[2,3,4]]) * np.array([2,3,4])

#  jupyter显示所有不同行输出变量

In [ ]:
# jupyter notebook/lab 默认输出只显示最后一行的变量
# 在文件的最上方添加：

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" 

"""
1. jupyter notebook/lab 默认输出只显示最后一行的变量，怎么显示所有的输出
在文件的最上方添加：

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "none" 


2.问题
Jupyter Notebook 默认状态下不会在代码左端显示行号，这就导致我们遇到报错时，无法正常调试。
解决：
点击View–>点击Toggle Line Numbers
就完成啦。

3. 问题：
jupyter原始界面亮瞎狗眼
解决：
更换主题颜色
使用 pip 命令安装 jupyterthemes：

pip install jupyterthemes

pip install --upgrade jupyterthem


jt -l                     L命令可以list当前已经安装的主题
jt -t grade3   -t命令是应用这个主题
jt -r，即可恢复至原来的白色背景


"""


In [ ]:
a = 2
a
c = 3
c

In [ ]:
# https://blog.csdn.net/luzhan66/article/details/82822896

# Python中__init__的用法和理解

#!/usr/bin/python
# -*- coding utf-8 -*-
#Created by Lu Zhan
 
class Box:
    def setDimension(self, width, height, depth):
        self.width = width
        self.height = height
        self.depth = depth
 
    def getVolume(self):
        return self.width * self.height * self.depth
    
    
    def getUse(self):
        return  self.depth
    
if __name__ == "__main__":
    b = Box()
    b.setDimension(10, 20, 30)
    print(b.getVolume())
    print(b.getUse())

# __init__()

In [ ]:
"""
我们在Box类中定义了setDimension方法去设定该Box的属性，这样过于繁琐，
而用__init__（）这个特殊的方法就可以方便地自己对类的属性进行定义，__init__()方法又被称为构造器（constructor）。
"""

#!/usr/bin/python
# -*- coding utf-8 -*-
#Created by Lu Zhan
 
class Box:
    #def setDimension(self, width, height, depth):
    #   self.width = width
    #   self.height = height
    #   self.depth = depth
    def __init__(self, width, height, depth):
        self.width = width
        self.height = height
        self.depth = depth
 
    def getVolume(self):
        return self.width * self.height * self.depth
if __name__ == "__main__":
    b = Box(10, 20, 30)
    print(b.getVolume())


# 类中调用该类的函数

In [ ]:
# 

__metaclass__ = type


class Stu:
    name = None
    age = None
    school = "华南理工大学"  #类变量，被所有学生实例共有

    def __init__(self, name, age):
        self.name = name
        self.age = age

    def printName_Age(self):
        print("我叫" + self.name + "," + "今年" + str(self.age) + "岁。")

    def printSchool(self):
        print("来自", Stu.school)

    def printTotal(self):
        print("类中方法调用类中的其他方法")
        #方法一：


#         Stu.printName_Age(self)
#         Stu.printSchool(self)
#         #方法二：
#         self.printName_Age()
#         self.printSchool()

# 使用类实现函数的功能

In [ ]:
class Hybrid:
    def __init__(self, color=10):
        self.color = color

    def col(self):
        return self.color**2


if __name__ == "__main__":
    D = Hybrid()
    print(D.col())

# python中函数接收多个参数

In [ ]:
"""
引入*args把多余的参数放入到元组中

https://www.cnblogs.com/hujianping/p/4726354.html

"""  
def fun(x, *args, **kw):
    print(kw)
    print(args)
    return x
    
print(fun(10,20,y=2,s=3))

# 9. 将两个数组合并成一个数组，多维数组变成一维数组

In [ ]:
 """
 1. extend()
 
 2. 直接相加
 
 3. flatten()
 
 """
    
c1 = ["Red","Green","Blue"]
c2 = ["Orange","Yellow","Indigo"]
c1.extend(c2)
c1 == ["Red","Green","Blue","Orange","Yellow","Indigo"]


c1 = ["Red","Green","Blue"]
c2 = ["Orange","Yellow","Indigo"]
c3 = c1 + c2
c3 == ["Red","Green","Blue","Orange","Yellow","Indigo"]


a = [[1,3],[2,4],[3,5]]
a = np.array(a)
a.flatten()



# # 1. 格式化输出和format()

[Python格式化输出 %s %d %f](https://blog.csdn.net/weixin_40583388/article/details/78600101?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.control&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.control)

In [ ]:
print('you are my family --%s, and %d'%('brother', 21))

print('low-rank/sparse = %.2f/%.2f\n' % (24, 34))

# 文件所在位置


In [ ]:
import sys
c = sys.executable
print(type(c)),c

# 函数有多个输出，只选择一个

In [ ]:
# 函数有多个输出，只选择一个
def aa(x, y, a, s):
    return x, y, a, s


y = aa(1, 2, 3, 4)[1]
print(y)

In [ ]:
a = np.arange(-10,10).reshape(4,5)
c = np.abs(a)
print("最小值为：{},对应的最小值的坐标为：{}".format(np.min(c), np.argmin(c)))

In [ ]:
np.where(c==np.min(c))

In [ ]:
print('Gamma = %g: Dens of A = %.1f%%, Dens of b = %.1f%%, Overlap = %.1f%%, Coverage = %.1f%%\n'\
                %(1,2,2,4,5))

# seed可以作为参数吗：

In [ ]:
def fun3(x,c,seed):
    print("x:",x, "c:", c, "seed:",seed)
fun3(2,1,1)


# dir

In [ ]:
 dir()

import numpy as np
#dir(np)


# 在Jupyter Notebook终止cell（代码块）而非终止（重启）整个Jupyter

当IPython的某个cell陷入死循环或长时间没有响应，想终止当前cell，但不想重启Kernel，可以这样做：

（1）在工具栏，点击Kernel（内核）子菜单中的Interrupt（中断）。

（2）在想终止的cell，按ESC键，让其脱离编辑状态，在命令状态中，连续按两次“I”键（interrupt的首字母）（简单：推荐）



# str.join(sequence)

参数

sequence -- 要连接的元素序列。

返回值

返回通过指定字符连接序列中元素后生成的新字符串。

实例

以下实例展示了join()的使用方法：

In [ ]:
#!/usr/bin/python
# -*- coding: UTF-8 -*-
 
str = "-";
seq = ("a", "b", "c"); # 字符串序列
str.join( seq )


# set(), list.count("abc") 

In [ ]:
# 找list是否可以排列为回文为回文
class Solution:
    def canPermutePalindrome(self, s):
        s_len = {}  # 统计每个字符的长度
        for i in set(s):
            s_len[i] = s.count(i)
        not_even = [i % 2 for i in s_len.values()] #统计每一个字符出现奇数次还是偶数次 
        if sum(not_even) == 1:
            return True
        else:
            return False
        
        
if __name__ == "__main__":
    s = 'aa'
    boo = Solution().canPermutePalindrome(s)
    print(boo)

# dict.get(key, default=None)

In [ ]:
"""
Python 字典(Dictionary) get()方法
描述
Python 字典(Dictionary) get() 函数返回指定键的值。

语法
get()方法语法：

dict.get(key, default=None)

参数
key -- 字典中要查找的键。
default -- 如果指定键的值不存在时，返回该默认值。
返回值
返回指定键的值，如果键不在字典中返回默认值 None 或者设置的默认值。


"""
class Solution:
    def canPermutePalindrome(self, s: str) -> bool:
        dic = {}
        for i in s:
            dic[i] = dic.get(i,0)+1
        count = 0
        for i in dic.values():
            if i%2==1:
                count+=1
        return count<2

    


# from collections import defaultdict

In [ ]:


"""
defaultdict()

defaultdict接受一个工厂函数作为参数，如下来构造：

dict =defaultdict( factory_function)
这个factory_function可以是list、set、str等等，作用是当key不存在时，返回的是工厂函数的默认值，比如list对应[ ]，str对应的是空字符串，set对应set( )，int对应0，如下举例：

"""
from collections import defaultdict

dict1 = defaultdict(int)
dict2 = defaultdict(set)
dict3 = defaultdict(str)
dict4 = defaultdict(list)
dict1[2] ='two'

print(dict1[1])
print(dict2[1])
print(dict3[1])
print(dict4[1])



 
from collections import defaultdict
dict1 = defaultdict(list)
dict1['name']




# from collections import Counter

In [ ]:
"""
Python collections.Counter(s)

统计字符串s中各个字符的个数

s = "loveleetcode"
# build hash map : character and how often it appears
count = collections.Counter(s)

"""
# 解题思路
# 使用Counter统计出各个字符出现次数
# 字符次数中的奇数为2个以下时为回文排列

# 代码

class Solution:
    def canPermutePalindrome(self, s: str) -> bool:
            odd = 0
            for x,i in Counter(s).items():
                if i % 2:
                    odd += 1
            return odd < 2

In [ ]:
import collections

# 统计字符串s中各个字符的个数

s = "loveleetcode"
# build hash map : character and how often it appears
count = collections.Counter(s)
count

# c.replace(' ', '%20')

In [ ]:
s = "We are happy."
print(s.replace(' ','%20'))
print(s)